
// Generated by Cadence Genus(TM) Synthesis Solution 22.11-s104_1
// Generated on: Apr 15 2025 01:15:35 PDT (Apr 15 2025 08:15:35 UTC)

// Verification Directory fv/DigitalLDOLogic 

module DigitalLDOLogic(clk, rst, comp_in, out);
  input clk, rst, comp_in;
  output [7:0] out;
  wire clk, rst, comp_in;
  wire [7:0] out;
  wire [7:0] pass;
  wire VDD, VSS, n_6, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_17;
  sky130_fd_sc_hd__dfxtp_1 \pass_reg[6] (.CLK (clk), .D (n_17), .Q
       (pass[6]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221o_1 g117__2398(.A1 (pass[7]), .A2 (n_14), .B1
       (pass[5]), .B2 (comp_in), .C1 (rst), .X (n_17), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g123(.A (pass[7]), .X (out[7]), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \pass_reg[4] (.CLK (clk), .D (n_13), .Q
       (pass[4]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \pass_reg[3] (.CLK (clk), .D (n_12), .Q
       (pass[3]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \pass_reg[5] (.CLK (clk), .D (n_15), .Q
       (pass[5]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \pass_reg[1] (.CLK (clk), .D (n_10), .Q
       (pass[1]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \pass_reg[2] (.CLK (clk), .D (n_11), .Q
       (pass[2]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \pass_reg[7] (.CLK (clk), .D (n_9), .Q
       (pass[7]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221o_1 g124__5107(.A1 (pass[6]), .A2 (n_14), .B1
       (pass[4]), .B2 (comp_in), .C1 (rst), .X (n_15), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221o_1 g130__6260(.A1 (pass[5]), .A2 (n_14), .B1
       (pass[3]), .B2 (comp_in), .C1 (rst), .X (n_13), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221o_1 g127__4319(.A1 (pass[4]), .A2 (n_14), .B1
       (pass[2]), .B2 (comp_in), .C1 (rst), .X (n_12), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221o_1 g128__8428(.A1 (pass[3]), .A2 (n_14), .B1
       (pass[1]), .B2 (comp_in), .C1 (rst), .X (n_11), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221o_1 g129__5526(.A1 (pass[2]), .A2 (n_14), .B1
       (pass[0]), .B2 (comp_in), .C1 (rst), .X (n_10), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \pass_reg[0] (.CLK (clk), .D (n_8), .Q
       (pass[0]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a21o_1 g131__6783(.A1 (n_6), .A2 (comp_in), .B1
       (rst), .X (n_9), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__or3_1 g132__3680(.A (comp_in), .B (rst), .C
       (pass[1]), .X (n_8), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__buf_8 g138(.A (n_6), .X (out[6]), .VGND (VSS), .VNB
       (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g137(.A (pass[0]), .X (out[0]), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g135(.A (pass[4]), .X (out[4]), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__clkbuf_1 g139(.A (pass[6]), .X (n_6), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__inv_1 g136(.A (comp_in), .Y (n_14), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g141(.A (pass[1]), .X (out[1]), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g140(.A (pass[2]), .X (out[2]), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g134(.A (pass[5]), .X (out[5]), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g133(.A (pass[3]), .X (out[3]), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
endmodule

