
// Generated by Cadence Genus(TM) Synthesis Solution 22.11-s104_1
// Generated on: Jul  5 2025 23:31:45 PDT (Jul  6 2025 06:31:45 UTC)

// Verification Directory fv/top_level_sr 

module CLKGATE_RC_CG_MOD(enable, ck_in, ck_out, test, VDD, VSS);
  input enable, ck_in, test;
  output ck_out;
  inout VDD, VSS;
  wire enable, ck_in, test;
  wire ck_out;
  wire VDD, VSS;
  sky130_fd_sc_hd__sdlclkp_1 RC_CGIC_INST(.GATE (enable), .CLK (ck_in),
       .SCE (test), .GCLK (ck_out), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
endmodule

module coarse_sr_PASS_NUM16(clk, rst, up, coarse_en, carry_in_incr,
     carry_in_decr, coarse_out, VDD, VSS);
  input clk, rst, up, coarse_en, carry_in_incr, carry_in_decr;
  output [15:0] coarse_out;
  inout VDD, VSS;
  wire clk, rst, up, coarse_en, carry_in_incr, carry_in_decr;
  wire [15:0] coarse_out;
  wire VDD, VSS;
  wire [15:0] coarse_out_next;
  wire CLKGATE_rc_gclk, UNCONNECTED, UNCONNECTED0, UNCONNECTED1,
       UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, UNCONNECTED5;
  wire UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9,
       UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, UNCONNECTED13;
  wire UNCONNECTED14, UNCONNECTED15, logic_0_1_net, logic_0_2_net,
       logic_0_3_net, logic_0_4_net, logic_0_5_net, logic_0_6_net;
  wire logic_0_7_net, logic_0_8_net, logic_0_9_net, logic_0_10_net,
       logic_0_11_net, logic_0_12_net, logic_0_13_net, logic_0_14_net;
  wire logic_0_15_net, logic_0_16_net, logic_0_17_net, n_0, n_1, n_2,
       n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_102, n_103;
  assign coarse_out_next[15] = 1'b0;
  assign coarse_out_next[14] = 1'b0;
  assign coarse_out_next[5] = 1'b0;
  assign coarse_out_next[11] = 1'b0;
  assign coarse_out_next[6] = 1'b0;
  assign coarse_out_next[3] = 1'b0;
  assign coarse_out_next[12] = 1'b0;
  assign coarse_out_next[8] = 1'b0;
  assign coarse_out_next[2] = 1'b0;
  assign coarse_out_next[0] = 1'b0;
  assign coarse_out_next[4] = 1'b0;
  assign coarse_out_next[7] = 1'b0;
  assign coarse_out_next[10] = 1'b0;
  assign coarse_out_next[9] = 1'b0;
  assign coarse_out_next[1] = 1'b0;
  assign coarse_out_next[13] = 1'b0;
  CLKGATE_RC_CG_MOD CLKGATE_RC_CG_HIER_INST0(.enable (n_103), .ck_in
       (clk), .ck_out (CLKGATE_rc_gclk), .test (logic_0_1_net), .VDD
       (VDD), .VSS (VSS));
  sky130_fd_sc_hd__o221ai_1 g1080__2398(.A1 (n_102), .A2 (n_67), .B1
       (n_70), .B2 (n_56), .C1 (n_74), .Y (coarse_out_next[13]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1081__5107(.A1 (n_72), .A2 (n_56), .B1
       (n_54), .B2 (n_57), .C1 (n_84), .Y (coarse_out_next[1]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1082__6260(.A1 (n_102), .A2 (n_68), .B1
       (n_59), .B2 (n_56), .C1 (n_85), .Y (coarse_out_next[9]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1083__4319(.A1 (n_102), .A2 (n_59), .B1
       (n_60), .B2 (n_56), .C1 (n_83), .Y (coarse_out_next[10]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1084__8428(.A1 (n_65), .A2 (n_56), .B1
       (n_102), .B2 (n_69), .C1 (n_81), .Y (coarse_out_next[7]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1085__5526(.A1 (n_102), .A2 (n_63), .B1
       (n_66), .B2 (n_56), .C1 (n_80), .Y (coarse_out_next[4]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1086__6783(.A1 (n_55), .A2 (n_61), .B1
       (carry_in_decr), .B2 (n_57), .C1 (n_54), .Y
       (coarse_out_next[0]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__o221ai_1 g1087__3680(.A1 (n_71), .A2 (n_56), .B1
       (n_54), .B2 (n_61), .C1 (n_75), .Y (coarse_out_next[2]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1088__1617(.A1 (n_68), .A2 (n_56), .B1
       (n_54), .B2 (n_69), .C1 (n_77), .Y (coarse_out_next[8]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1089__2802(.A1 (n_67), .A2 (n_56), .B1
       (n_54), .B2 (n_60), .C1 (n_76), .Y (coarse_out_next[12]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1090__1705(.A1 (n_63), .A2 (n_56), .B1
       (n_54), .B2 (n_72), .C1 (n_82), .Y (coarse_out_next[3]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1091__5122(.A1 (n_69), .A2 (n_56), .B1
       (n_54), .B2 (n_66), .C1 (n_79), .Y (coarse_out_next[6]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1092__8246(.A1 (n_62), .A2 (n_56), .B1
       (n_54), .B2 (n_59), .C1 (n_73), .Y (coarse_out_next[11]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1093__7098(.A1 (n_64), .A2 (n_56), .B1
       (n_54), .B2 (n_63), .C1 (n_78), .Y (coarse_out_next[5]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o221ai_1 g1094__6131(.A1 (n_102), .A2 (n_70), .B1
       (n_54), .B2 (n_67), .C1 (n_36), .Y (coarse_out_next[14]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221o_1 g1095__1881(.A1 (n_58), .A2 (n_54), .B1
       (carry_in_incr), .B2 (up), .C1 (rst), .X (n_103), .VGND (VSS),
       .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o21ai_0 g1096__5115(.A1 (n_54), .A2 (n_70), .B1
       (n_35), .Y (coarse_out_next[15]), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1097__7482(.A (n_54), .B (n_65), .X (n_85),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1098__4733(.A (n_102), .B (n_61), .X (n_84),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1099__6161(.A (n_54), .B (n_68), .X (n_83),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1100__9315(.A (n_102), .B (n_71), .X (n_82),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1101__9945(.A (n_54), .B (n_64), .X (n_81),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1102__2883(.A (n_54), .B (n_71), .X (n_80),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1103__2346(.A (n_102), .B (n_64), .X (n_79),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1104__1666(.A (n_102), .B (n_66), .X (n_78),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1105__7410(.A (n_102), .B (n_65), .X (n_77),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1106__6417(.A (n_102), .B (n_62), .X (n_76),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1107__5477(.A (n_102), .B (n_72), .X (n_75),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1108__2398(.A (n_54), .B (n_62), .X (n_74),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g1109__5107(.A (n_102), .B (n_60), .X (n_73),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1112__6260(.A0 (n_42), .A1 (n_51), .S (up),
       .Y (n_72), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1113__4319(.A0 (n_43), .A1 (n_40), .S (up),
       .Y (n_71), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1114__8428(.A0 (n_37), .A1 (n_41), .S (up),
       .Y (n_70), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1115__5526(.A0 (n_49), .A1 (n_46), .S (up),
       .Y (n_69), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1116__6783(.A0 (n_44), .A1 (n_49), .S (up),
       .Y (n_68), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1117__3680(.A0 (n_52), .A1 (n_50), .S (up),
       .Y (n_67), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1118__1617(.A0 (n_46), .A1 (n_43), .S (up),
       .Y (n_66), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2_2 g1119__2802(.A0 (coarse_en), .A1 (n_53), .S
       (carry_in_decr), .X (n_58), .VGND (VSS), .VNB (VSS), .VPB (VDD),
       .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1120__1705(.A0 (n_39), .A1 (n_48), .S (up),
       .Y (n_65), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1121__5122(.A0 (n_48), .A1 (n_45), .S (up),
       .Y (n_64), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1122__8246(.A0 (n_45), .A1 (n_42), .S (up),
       .Y (n_63), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1123__7098(.A0 (n_41), .A1 (n_47), .S (up),
       .Y (n_62), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1124__6131(.A0 (n_40), .A1 (n_38), .S (up),
       .Y (n_61), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1125__1881(.A0 (n_50), .A1 (n_44), .S (up),
       .Y (n_60), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g1126__5115(.A0 (n_47), .A1 (n_39), .S (up),
       .Y (n_59), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g1127__7482(.A (up), .B (n_51), .Y (n_57),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nand2_1 g1130__4733(.A (n_54), .B (carry_in_decr),
       .Y (n_56), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nand2_1 g1131__6161(.A (n_54), .B (n_55), .Y
       (n_102), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__clkinv_1 g1132(.A (carry_in_decr), .Y (n_55), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__inv_2 g1133(.A (carry_in_incr), .Y (n_54), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__inv_2 g1134(.A (up), .Y (n_53), .VGND (VSS), .VNB
       (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dlygate4sd1_1 drc_bufs1190(.A (coarse_out[0]), .X
       (n_38), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dlygate4sd1_1 drc_bufs1191(.A (coarse_out[15]), .X
       (n_37), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1192(.A (coarse_out[14]), .X (n_52),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1193(.A (coarse_out[12]), .X (n_50),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1194(.A (coarse_out[8]), .X (n_49),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1195(.A (coarse_out[7]), .X (n_48),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1196(.A (coarse_out[11]), .X (n_47),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1197(.A (coarse_out[6]), .X (n_46),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1198(.A (coarse_out[5]), .X (n_45),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1199(.A (coarse_out[13]), .X (n_41),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1200(.A (coarse_out[10]), .X (n_44),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1201(.A (coarse_out[4]), .X (n_43),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1202(.A (coarse_out[3]), .X (n_42),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1203(.A (coarse_out[9]), .X (n_39),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1204(.A (coarse_out[2]), .X (n_40),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_2 drc_bufs1205(.A (coarse_out[1]), .X (n_51),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nand3b_1 g2__9315(.A_N (n_56), .B (n_52), .C (up),
       .Y (n_36), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nand3b_1 g1240__9945(.A_N (n_102), .B (n_52), .C
       (up), .Y (n_35), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[0] (.CLK (clk), .D (n_18),
       .Q (n_19), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[15] (.CLK (clk), .D (n_17),
       .Q (n_34), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g688__2883(.A (rst), .B (n_15), .Y (n_18),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g689__2346(.A (rst), .B (n_16), .Y (n_17),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__mux2i_1 g690__1666(.A0 (logic_0_2_net), .A1 (n_34),
       .S (n_14), .Y (n_16), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__mux2i_1 g691__7410(.A0 (logic_0_3_net), .A1 (n_19),
       .S (n_14), .Y (n_15), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[2] (.CLK (CLKGATE_rc_gclk),
       .D (n_13), .Q (n_21), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[12] (.CLK (CLKGATE_rc_gclk),
       .D (n_12), .Q (n_31), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[13] (.CLK (CLKGATE_rc_gclk),
       .D (n_11), .Q (n_32), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[10] (.CLK (CLKGATE_rc_gclk),
       .D (n_7), .Q (n_29), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[14] (.CLK (CLKGATE_rc_gclk),
       .D (n_10), .Q (n_33), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[1] (.CLK (CLKGATE_rc_gclk),
       .D (n_8), .Q (n_20), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[11] (.CLK (CLKGATE_rc_gclk),
       .D (n_9), .Q (n_30), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[9] (.CLK (CLKGATE_rc_gclk),
       .D (n_0), .Q (n_28), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[4] (.CLK (CLKGATE_rc_gclk),
       .D (n_6), .Q (n_23), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[5] (.CLK (CLKGATE_rc_gclk),
       .D (n_5), .Q (n_24), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[6] (.CLK (CLKGATE_rc_gclk),
       .D (n_4), .Q (n_25), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[7] (.CLK (CLKGATE_rc_gclk),
       .D (n_2), .Q (n_26), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[8] (.CLK (CLKGATE_rc_gclk),
       .D (n_1), .Q (n_27), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 \coarse_out_reg[3] (.CLK (CLKGATE_rc_gclk),
       .D (n_3), .Q (n_22), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__nor2b_1 g706__6417(.A (rst), .B_N (logic_0_4_net),
       .Y (n_13), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g707__5477(.A (rst), .B_N (logic_0_5_net),
       .Y (n_12), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g708__2398(.A (rst), .B_N (logic_0_6_net),
       .Y (n_11), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g709__5107(.A (rst), .B_N (logic_0_7_net),
       .Y (n_10), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g710__6260(.A (rst), .B_N (logic_0_8_net),
       .Y (n_9), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g711__4319(.A (rst), .B_N (logic_0_9_net),
       .Y (n_8), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g712__8428(.A (coarse_en), .B (n_102), .Y
       (n_14), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g713__5526(.A (rst), .B_N (logic_0_10_net),
       .Y (n_7), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g714__6783(.A (rst), .B_N (logic_0_11_net),
       .Y (n_6), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g715__3680(.A (rst), .B_N (logic_0_12_net),
       .Y (n_5), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g716__1617(.A (rst), .B_N (logic_0_13_net),
       .Y (n_4), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g717__2802(.A (rst), .B_N (logic_0_14_net),
       .Y (n_3), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g718__1705(.A (rst), .B_N (logic_0_15_net),
       .Y (n_2), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g719__5122(.A (rst), .B_N (logic_0_16_net),
       .Y (n_1), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2b_1 g720__8246(.A (rst), .B_N (logic_0_17_net),
       .Y (n_0), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g721(.A (n_19), .X (coarse_out[0]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g722(.A (n_34), .X (coarse_out[15]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs(.A (n_33), .X (coarse_out[14]), .VGND
       (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs723(.A (n_20), .X (coarse_out[1]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs724(.A (n_21), .X (coarse_out[2]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs725(.A (n_22), .X (coarse_out[3]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs726(.A (n_23), .X (coarse_out[4]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs727(.A (n_24), .X (coarse_out[5]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs728(.A (n_25), .X (coarse_out[6]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs729(.A (n_26), .X (coarse_out[7]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs730(.A (n_31), .X (coarse_out[12]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs731(.A (n_28), .X (coarse_out[9]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs732(.A (n_29), .X (coarse_out[10]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs733(.A (n_30), .X (coarse_out[11]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs734(.A (n_27), .X (coarse_out[8]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 drc_bufs735(.A (n_32), .X (coarse_out[13]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell(.HI (UNCONNECTED), .LO
       (logic_0_1_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell1(.HI (UNCONNECTED0), .LO
       (logic_0_2_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell2(.HI (UNCONNECTED1), .LO
       (logic_0_3_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell3(.HI (UNCONNECTED2), .LO
       (logic_0_4_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell4(.HI (UNCONNECTED3), .LO
       (logic_0_5_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell5(.HI (UNCONNECTED4), .LO
       (logic_0_6_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell6(.HI (UNCONNECTED5), .LO
       (logic_0_7_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell7(.HI (UNCONNECTED6), .LO
       (logic_0_8_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell8(.HI (UNCONNECTED7), .LO
       (logic_0_9_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell9(.HI (UNCONNECTED8), .LO
       (logic_0_10_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell10(.HI (UNCONNECTED9), .LO
       (logic_0_11_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell11(.HI (UNCONNECTED10), .LO
       (logic_0_12_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell12(.HI (UNCONNECTED11), .LO
       (logic_0_13_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell13(.HI (UNCONNECTED12), .LO
       (logic_0_14_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell14(.HI (UNCONNECTED13), .LO
       (logic_0_15_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell15(.HI (UNCONNECTED14), .LO
       (logic_0_16_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell16(.HI (UNCONNECTED15), .LO
       (logic_0_17_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
endmodule

module CLKGATE_RC_CG_MOD_1(enable, ck_in, ck_out, test, VDD, VSS);
  input enable, ck_in, test;
  output ck_out;
  inout VDD, VSS;
  wire enable, ck_in, test;
  wire ck_out;
  wire VDD, VSS;
  sky130_fd_sc_hd__sdlclkp_1 RC_CGIC_INST(.GATE (enable), .CLK (ck_in),
       .SCE (test), .GCLK (ck_out), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
endmodule

module fine_sr_PASS_NUM16(clk, rst, comp_in, fine_en, fine_out,
     carry_out_incr, carry_out_decr, VDD, VSS);
  input clk, rst, comp_in, fine_en;
  output [15:0] fine_out;
  output carry_out_incr, carry_out_decr;
  inout VDD, VSS;
  wire clk, rst, comp_in, fine_en;
  wire [15:0] fine_out;
  wire carry_out_incr, carry_out_decr;
  wire VDD, VSS;
  wire CLKGATE_rc_gclk, UNCONNECTED16, all_ones, \fine_out[0]_190 ,
       \fine_out[1]_191 , \fine_out[2]_192 , \fine_out[3]_193 ,
       \fine_out[4]_194 ;
  wire \fine_out[5]_195 , \fine_out[6]_196 , \fine_out[7]_197 ,
       \fine_out[8]_198 , \fine_out[9]_199 , \fine_out[10]_200 ,
       \fine_out[11]_201 , \fine_out[12]_202 ;
  wire \fine_out[13]_203 , \fine_out[14]_204 , \fine_out[15]_205 ,
       logic_0_1_net, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_62, n_63, n_64, n_66;
  CLKGATE_RC_CG_MOD_1 CLKGATE_RC_CG_HIER_INST1(.enable (n_63), .ck_in
       (clk), .ck_out (CLKGATE_rc_gclk), .test (logic_0_1_net), .VDD
       (VDD), .VSS (VSS));
  sky130_fd_sc_hd__inv_1 g629(.A (n_64), .Y (n_62), .VGND (VSS), .VNB
       (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g642(.A (\fine_out[12]_202 ), .X
       (fine_out[12]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__buf_8 g644(.A (\fine_out[7]_197 ), .X (fine_out[7]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g632(.A (\fine_out[11]_201 ), .X
       (fine_out[11]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__buf_8 g634(.A (\fine_out[4]_194 ), .X (fine_out[4]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g635(.A (\fine_out[13]_203 ), .X
       (fine_out[13]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__buf_8 g645(.A (\fine_out[1]_191 ), .X (fine_out[1]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g638(.A (\fine_out[2]_192 ), .X (fine_out[2]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g630(.A (\fine_out[10]_200 ), .X
       (fine_out[10]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__buf_8 g643(.A (\fine_out[9]_199 ), .X (fine_out[9]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g633(.A (\fine_out[6]_196 ), .X (fine_out[6]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g631(.A (\fine_out[8]_198 ), .X (fine_out[8]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g636(.A (\fine_out[0]_190 ), .X (fine_out[0]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g639(.A (\fine_out[15]_205 ), .X
       (fine_out[15]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__buf_8 g637(.A (\fine_out[5]_195 ), .X (fine_out[5]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g641(.A (\fine_out[3]_193 ), .X (fine_out[3]),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__buf_8 g640(.A (\fine_out[14]_204 ), .X
       (fine_out[14]), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 carry_out_decr_reg(.CLK (clk), .D (n_45), .Q
       (carry_out_decr), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__dfxtp_1 carry_out_incr_reg(.CLK (clk), .D (n_44), .Q
       (carry_out_incr), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__nor3b_1 g741__7098(.A (rst), .B (n_66), .C_N
       (fine_en), .Y (n_45), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__nor4bb_1 g742__6131(.A (rst), .B (all_ones), .C_N
       (fine_en), .D_N (comp_in), .Y (n_44), .VGND (VSS), .VNB (VSS),
       .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_1 g743__1881(.A (comp_in), .B (n_64), .X (n_66),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nand4_1 g744__5115(.A (n_39), .B (n_37), .C (n_38),
       .D (n_36), .Y (n_64), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
  sky130_fd_sc_hd__nand4_1 g745__7482(.A (n_41), .B (n_42), .C (n_40),
       .D (n_43), .Y (all_ones), .VGND (VSS), .VNB (VSS), .VPB (VDD),
       .VPWR (VDD));
  sky130_fd_sc_hd__and4_1 g746__4733(.A (\fine_out[11]_201 ), .B
       (\fine_out[10]_200 ), .C (\fine_out[9]_199 ), .D
       (\fine_out[8]_198 ), .X (n_43), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__and4_1 g747__6161(.A (\fine_out[7]_197 ), .B
       (\fine_out[6]_196 ), .C (\fine_out[5]_195 ), .D
       (\fine_out[4]_194 ), .X (n_42), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__and4_1 g748__9315(.A (\fine_out[15]_205 ), .B
       (\fine_out[14]_204 ), .C (\fine_out[13]_203 ), .D
       (\fine_out[12]_202 ), .X (n_41), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__and4_1 g749__9945(.A (\fine_out[2]_192 ), .B
       (\fine_out[1]_191 ), .C (\fine_out[3]_193 ), .D
       (\fine_out[0]_190 ), .X (n_40), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor4_1 g750__2883(.A (\fine_out[12]_202 ), .B
       (\fine_out[14]_204 ), .C (\fine_out[15]_205 ), .D
       (\fine_out[13]_203 ), .Y (n_39), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor4_1 g751__2346(.A (\fine_out[0]_190 ), .B
       (\fine_out[5]_195 ), .C (\fine_out[6]_196 ), .D
       (\fine_out[7]_197 ), .Y (n_38), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor4_1 g752__1666(.A (\fine_out[8]_198 ), .B
       (\fine_out[10]_200 ), .C (\fine_out[11]_201 ), .D
       (\fine_out[9]_199 ), .Y (n_37), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor4_1 g753__7410(.A (\fine_out[1]_191 ), .B
       (\fine_out[3]_193 ), .C (\fine_out[4]_194 ), .D
       (\fine_out[2]_192 ), .Y (n_36), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__or2_2 g754__6417(.A (fine_en), .B (rst), .X (n_63),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[0] (.CLK (CLKGATE_rc_gclk), .D
       (n_20), .Q (\fine_out[0]_190 ), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[1] (.CLK (CLKGATE_rc_gclk), .D
       (n_28), .Q (\fine_out[1]_191 ), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[6] (.CLK (CLKGATE_rc_gclk), .D
       (n_22), .Q (\fine_out[6]_196 ), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[7] (.CLK (CLKGATE_rc_gclk), .D
       (n_31), .Q (\fine_out[7]_197 ), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[8] (.CLK (CLKGATE_rc_gclk), .D
       (n_33), .Q (\fine_out[8]_198 ), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[2] (.CLK (CLKGATE_rc_gclk), .D
       (n_34), .Q (\fine_out[2]_192 ), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[9] (.CLK (CLKGATE_rc_gclk), .D
       (n_32), .Q (\fine_out[9]_199 ), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[3] (.CLK (CLKGATE_rc_gclk), .D
       (n_35), .Q (\fine_out[3]_193 ), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[15] (.CLK (CLKGATE_rc_gclk),
       .D (n_21), .Q (\fine_out[15]_205 ), .VGND (VSS), .VNB (VSS),
       .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[11] (.CLK (CLKGATE_rc_gclk),
       .D (n_29), .Q (\fine_out[11]_201 ), .VGND (VSS), .VNB (VSS),
       .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[4] (.CLK (CLKGATE_rc_gclk), .D
       (n_25), .Q (\fine_out[4]_194 ), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[12] (.CLK (CLKGATE_rc_gclk),
       .D (n_23), .Q (\fine_out[12]_202 ), .VGND (VSS), .VNB (VSS),
       .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[10] (.CLK (CLKGATE_rc_gclk),
       .D (n_30), .Q (\fine_out[10]_200 ), .VGND (VSS), .VNB (VSS),
       .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[5] (.CLK (CLKGATE_rc_gclk), .D
       (n_24), .Q (\fine_out[5]_195 ), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[14] (.CLK (CLKGATE_rc_gclk),
       .D (n_27), .Q (\fine_out[14]_204 ), .VGND (VSS), .VNB (VSS),
       .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__dfxtp_1 \fine_out_reg[13] (.CLK (CLKGATE_rc_gclk),
       .D (n_26), .Q (\fine_out[13]_203 ), .VGND (VSS), .VNB (VSS),
       .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g849__5477(.A (rst), .B (n_14), .Y (n_35),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g850__2398(.A (rst), .B (n_17), .Y (n_34),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g851__5107(.A (rst), .B (n_16), .Y (n_33),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g852__6260(.A (rst), .B (n_15), .Y (n_32),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g853__4319(.A (rst), .B (n_13), .Y (n_31),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g854__8428(.A (rst), .B (n_19), .Y (n_30),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g855__5526(.A (rst), .B (n_6), .Y (n_29),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g856__6783(.A (rst), .B (n_12), .Y (n_28),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g857__3680(.A (rst), .B (n_18), .Y (n_27),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g858__1617(.A (rst), .B (n_9), .Y (n_26),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g859__2802(.A (rst), .B (n_11), .Y (n_25),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g860__1705(.A (rst), .B (n_8), .Y (n_24),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g861__5122(.A (rst), .B (n_10), .Y (n_23),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nor2_1 g862__8246(.A (rst), .B (n_7), .Y (n_22),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a21oi_1 g863__7098(.A1 (n_5), .A2 (n_66), .B1 (rst),
       .Y (n_21), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a21oi_1 g864__6131(.A1 (n_2), .A2 (n_4), .B1 (rst),
       .Y (n_20), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g865__1881(.A1 (\fine_out[11]_201 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[9]_199 ), .C1 (n_1), .Y (n_19),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g866__5115(.A1 (\fine_out[15]_205 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[13]_203 ), .C1 (n_1), .Y
       (n_18), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g867__7482(.A1 (\fine_out[3]_193 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[1]_191 ), .C1 (n_1), .Y (n_17),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g868__4733(.A1 (\fine_out[9]_199 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[7]_197 ), .C1 (n_1), .Y (n_16),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g869__6161(.A1 (\fine_out[10]_200 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[8]_198 ), .C1 (n_1), .Y (n_15),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g870__9315(.A1 (\fine_out[4]_194 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[2]_192 ), .C1 (n_1), .Y (n_14),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g871__9945(.A1 (\fine_out[8]_198 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[6]_196 ), .C1 (n_1), .Y (n_13),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g872__2883(.A1 (\fine_out[2]_192 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[0]_190 ), .C1 (n_1), .Y (n_12),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g873__2346(.A1 (\fine_out[5]_195 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[3]_193 ), .C1 (n_1), .Y (n_11),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g874__1666(.A1 (\fine_out[13]_203 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[11]_201 ), .C1 (n_1), .Y
       (n_10), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g875__7410(.A1 (\fine_out[14]_204 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[12]_202 ), .C1 (n_1), .Y (n_9),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g876__6417(.A1 (\fine_out[6]_196 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[4]_194 ), .C1 (n_1), .Y (n_8),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g877__5477(.A1 (\fine_out[7]_197 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[5]_195 ), .C1 (n_1), .Y (n_7),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__a221oi_1 g878__2398(.A1 (\fine_out[12]_202 ), .A2
       (n_0), .B1 (n_3), .B2 (\fine_out[10]_200 ), .C1 (n_1), .Y (n_6),
       .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nand2_1 g879__5107(.A (n_3), .B (\fine_out[14]_204
       ), .Y (n_5), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__o21ai_1 g880__6260(.A1 (\fine_out[1]_191 ), .A2
       (n_62), .B1 (n_0), .Y (n_4), .VGND (VSS), .VNB (VSS), .VPB
       (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__inv_2 g881(.A (n_2), .Y (n_3), .VGND (VSS), .VNB
       (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__nand2_1 g882__4319(.A (all_ones), .B (comp_in), .Y
       (n_2), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__inv_2 g891(.A (n_66), .Y (n_1), .VGND (VSS), .VNB
       (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__inv_2 g899(.A (comp_in), .Y (n_0), .VGND (VSS), .VNB
       (VSS), .VPB (VDD), .VPWR (VDD));
  sky130_fd_sc_hd__conb_1 tie_0_cell(.HI (UNCONNECTED16), .LO
       (logic_0_1_net), .VGND (VSS), .VNB (VSS), .VPB (VDD), .VPWR
       (VDD));
endmodule

module top_level_sr(clk, rst, comp_in, up, fine_en, coarse_en,
     fine_out, coarse_out);
  input clk, rst, comp_in, up, fine_en, coarse_en;
  output [15:0] fine_out, coarse_out;
  wire clk, rst, comp_in, up, fine_en, coarse_en;
  wire [15:0] fine_out, coarse_out;
  wire VDD, VSS;
  wire carry_decr, carry_incr;
  coarse_sr_PASS_NUM16 coarse_sr(.clk (clk), .rst (rst), .up (up),
       .coarse_en (coarse_en), .carry_in_incr (carry_incr),
       .carry_in_decr (carry_decr), .coarse_out (coarse_out), .VDD
       (VDD), .VSS (VSS));
  fine_sr_PASS_NUM16 fine_sr(.clk (clk), .rst (rst), .comp_in
       (comp_in), .fine_en (fine_en), .fine_out (fine_out),
       .carry_out_incr (carry_incr), .carry_out_decr (carry_decr), .VDD
       (VDD), .VSS (VSS));
endmodule

