$ Spice netlist generated by v2lvs
$ v2024.3_16.10    Tue Jul 9 11:27:02 PDT 2024
.INCLUDE "/home/aa/users/cs199-apt/Downloads/sky130_fd_sc_hd.spice" 
*.BUSDELIMITER [ 

.SUBCKT DigitalLDOLogic clk rst comp_in out[255] out[254] out[253] out[252] 
+ out[251] out[250] out[249] out[248] out[247] out[246] out[245] out[244] 
+ out[243] out[242] out[241] out[240] out[239] out[238] out[237] out[236] 
+ out[235] out[234] out[233] out[232] out[231] out[230] out[229] out[228] 
+ out[227] out[226] out[225] out[224] out[223] out[222] out[221] out[220] 
+ out[219] out[218] out[217] out[216] out[215] out[214] out[213] out[212] 
+ out[211] out[210] out[209] out[208] out[207] out[206] out[205] out[204] 
+ out[203] out[202] out[201] out[200] out[199] out[198] out[197] out[196] 
+ out[195] out[194] out[193] out[192] out[191] out[190] out[189] out[188] 
+ out[187] out[186] out[185] out[184] out[183] out[182] out[181] out[180] 
+ out[179] out[178] out[177] out[176] out[175] out[174] out[173] out[172] 
+ out[171] out[170] out[169] out[168] out[167] out[166] out[165] out[164] 
+ out[163] out[162] out[161] out[160] out[159] out[158] out[157] out[156] 
+ out[155] out[154] out[153] out[152] out[151] out[150] out[149] out[148] 
+ out[147] out[146] out[145] out[144] out[143] out[142] out[141] out[140] 
+ out[139] out[138] out[137] out[136] out[135] out[134] out[133] out[132] 
+ out[131] out[130] out[129] out[128] out[127] out[126] out[125] out[124] 
+ out[123] out[122] out[121] out[120] out[119] out[118] out[117] out[116] 
+ out[115] out[114] out[113] out[112] out[111] out[110] out[109] out[108] 
+ out[107] out[106] out[105] out[104] out[103] out[102] out[101] out[100] 
+ out[99] out[98] out[97] out[96] out[95] out[94] out[93] out[92] out[91] 
+ out[90] out[89] out[88] out[87] out[86] out[85] out[84] out[83] out[82] 
+ out[81] out[80] out[79] out[78] out[77] out[76] out[75] out[74] out[73] 
+ out[72] out[71] out[70] out[69] out[68] out[67] out[66] out[65] out[64] 
+ out[63] out[62] out[61] out[60] out[59] out[58] out[57] out[56] out[55] 
+ out[54] out[53] out[52] out[51] out[50] out[49] out[48] out[47] out[46] 
+ out[45] out[44] out[43] out[42] out[41] out[40] out[39] out[38] out[37] 
+ out[36] out[35] out[34] out[33] out[32] out[31] out[30] out[29] out[28] 
+ out[27] out[26] out[25] out[24] out[23] out[22] out[21] out[20] out[19] 
+ out[18] out[17] out[16] out[15] out[14] out[13] out[12] out[11] out[10] 
+ out[9] out[8] out[7] out[6] out[5] out[4] out[3] out[2] out[1] out[0] VDD VSS 
Xpass_reg[254] clk n_513 VSS VSS VDD VDD pass[254] sky130_fd_sc_hd__dfxtp_1 
Xg4333__2398 pass[255] n_923 pass[253] n_521 n_713 VSS VSS VDD VDD n_513 
+ sky130_fd_sc_hd__a221o_1 
Xpass_reg[183] clk n_333 VSS VSS VDD VDD pass[183] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[49] clk n_326 VSS VSS VDD VDD pass[49] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[226] clk n_500 VSS VSS VDD VDD pass[226] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[4] clk n_400 VSS VSS VDD VDD pass[4] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[50] clk n_325 VSS VSS VDD VDD pass[50] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[51] clk n_492 VSS VSS VDD VDD pass[51] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[153] clk n_496 VSS VSS VDD VDD pass[153] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[154] clk n_495 VSS VSS VDD VDD pass[154] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[155] clk n_489 VSS VSS VDD VDD pass[155] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[143] clk n_346 VSS VSS VDD VDD pass[143] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[52] clk n_485 VSS VSS VDD VDD pass[52] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[156] clk n_483 VSS VSS VDD VDD pass[156] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[157] clk n_480 VSS VSS VDD VDD pass[157] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[140] clk n_350 VSS VSS VDD VDD pass[140] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[158] clk n_472 VSS VSS VDD VDD pass[158] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[53] clk n_477 VSS VSS VDD VDD pass[53] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[54] clk n_454 VSS VSS VDD VDD pass[54] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[138] clk n_355 VSS VSS VDD VDD pass[138] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[159] clk n_471 VSS VSS VDD VDD pass[159] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[160] clk n_468 VSS VSS VDD VDD pass[160] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[161] clk n_465 VSS VSS VDD VDD pass[161] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[55] clk n_461 VSS VSS VDD VDD pass[55] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[162] clk n_457 VSS VSS VDD VDD pass[162] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[163] clk n_448 VSS VSS VDD VDD pass[163] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[56] clk n_453 VSS VSS VDD VDD pass[56] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[41] clk n_364 VSS VSS VDD VDD pass[41] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[164] clk n_511 VSS VSS VDD VDD pass[164] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[57] clk n_429 VSS VSS VDD VDD pass[57] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[58] clk n_424 VSS VSS VDD VDD pass[58] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[40] clk n_373 VSS VSS VDD VDD pass[40] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[165] clk n_441 VSS VSS VDD VDD pass[165] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[166] clk n_437 VSS VSS VDD VDD pass[166] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[167] clk n_432 VSS VSS VDD VDD pass[167] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[39] clk n_378 VSS VSS VDD VDD pass[39] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[168] clk n_423 VSS VSS VDD VDD pass[168] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[59] clk n_406 VSS VSS VDD VDD pass[59] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[169] clk n_420 VSS VSS VDD VDD pass[169] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[170] clk n_413 VSS VSS VDD VDD pass[170] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[171] clk n_405 VSS VSS VDD VDD pass[171] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[60] clk n_399 VSS VSS VDD VDD pass[60] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[172] clk n_396 VSS VSS VDD VDD pass[172] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[122] clk n_392 VSS VSS VDD VDD pass[122] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[173] clk n_387 VSS VSS VDD VDD pass[173] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[174] clk n_381 VSS VSS VDD VDD pass[174] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[61] clk n_384 VSS VSS VDD VDD pass[61] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[120] clk n_395 VSS VSS VDD VDD pass[120] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[175] clk n_376 VSS VSS VDD VDD pass[175] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[176] clk n_358 VSS VSS VDD VDD pass[176] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[62] clk n_369 VSS VSS VDD VDD pass[62] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[33] clk n_398 VSS VSS VDD VDD pass[33] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[177] clk n_365 VSS VSS VDD VDD pass[177] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[5] clk n_372 VSS VSS VDD VDD pass[5] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[6] clk n_345 VSS VSS VDD VDD pass[6] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[63] clk n_361 VSS VSS VDD VDD pass[63] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[64] clk n_352 VSS VSS VDD VDD pass[64] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[178] clk n_357 VSS VSS VDD VDD pass[178] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[179] clk n_351 VSS VSS VDD VDD pass[179] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[112] clk n_415 VSS VSS VDD VDD pass[112] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[180] clk n_348 VSS VSS VDD VDD pass[180] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[65] clk n_339 VSS VSS VDD VDD pass[65] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[181] clk n_341 VSS VSS VDD VDD pass[181] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[109] clk n_421 VSS VSS VDD VDD pass[109] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[182] clk n_336 VSS VSS VDD VDD pass[182] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[152] clk n_259 VSS VSS VDD VDD pass[152] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[184] clk n_324 VSS VSS VDD VDD pass[184] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[106] clk n_430 VSS VSS VDD VDD pass[106] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[7] clk n_328 VSS VSS VDD VDD pass[7] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[66] clk n_327 VSS VSS VDD VDD pass[66] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[185] clk n_447 VSS VSS VDD VDD pass[185] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[67] clk n_321 VSS VSS VDD VDD pass[67] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[186] clk n_383 VSS VSS VDD VDD pass[186] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[187] clk n_318 VSS VSS VDD VDD pass[187] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[8] clk n_319 VSS VSS VDD VDD pass[8] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[25] clk n_439 VSS VSS VDD VDD pass[25] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[68] clk n_317 VSS VSS VDD VDD pass[68] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[188] clk n_316 VSS VSS VDD VDD pass[188] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[189] clk n_315 VSS VSS VDD VDD pass[189] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[21] clk n_469 VSS VSS VDD VDD pass[21] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[190] clk n_313 VSS VSS VDD VDD pass[190] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[9] clk n_308 VSS VSS VDD VDD pass[9] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[69] clk n_314 VSS VSS VDD VDD pass[69] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[251] clk n_445 VSS VSS VDD VDD pass[251] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[70] clk n_311 VSS VSS VDD VDD pass[70] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[191] clk n_312 VSS VSS VDD VDD pass[191] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[192] clk n_310 VSS VSS VDD VDD pass[192] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[193] clk n_309 VSS VSS VDD VDD pass[193] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[71] clk n_307 VSS VSS VDD VDD pass[71] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[194] clk n_306 VSS VSS VDD VDD pass[194] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[195] clk n_305 VSS VSS VDD VDD pass[195] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[246] clk n_456 VSS VSS VDD VDD pass[246] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[72] clk n_301 VSS VSS VDD VDD pass[72] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[196] clk n_389 VSS VSS VDD VDD pass[196] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[10] clk n_300 VSS VSS VDD VDD pass[10] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[96] clk n_463 VSS VSS VDD VDD pass[96] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[73] clk n_295 VSS VSS VDD VDD pass[73] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[197] clk n_296 VSS VSS VDD VDD pass[197] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[198] clk n_294 VSS VSS VDD VDD pass[198] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[22] clk n_452 VSS VSS VDD VDD pass[22] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[199] clk n_293 VSS VSS VDD VDD pass[199] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[200] clk n_292 VSS VSS VDD VDD pass[200] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[11] clk n_298 VSS VSS VDD VDD pass[11] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[74] clk n_299 VSS VSS VDD VDD pass[74] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[201] clk n_302 VSS VSS VDD VDD pass[201] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[75] clk n_291 VSS VSS VDD VDD pass[75] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[202] clk n_304 VSS VSS VDD VDD pass[202] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[237] clk n_475 VSS VSS VDD VDD pass[237] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[203] clk n_290 VSS VSS VDD VDD pass[203] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[13] clk n_273 VSS VSS VDD VDD pass[13] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[14] clk n_268 VSS VSS VDD VDD pass[14] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[235] clk n_478 VSS VSS VDD VDD pass[235] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[76] clk n_286 VSS VSS VDD VDD pass[76] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[204] clk n_502 VSS VSS VDD VDD pass[204] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[205] clk n_285 VSS VSS VDD VDD pass[205] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[90] clk n_486 VSS VSS VDD VDD pass[90] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[206] clk n_284 VSS VSS VDD VDD pass[206] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[77] clk n_287 VSS VSS VDD VDD pass[77] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[207] clk n_283 VSS VSS VDD VDD pass[207] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[208] clk n_281 VSS VSS VDD VDD pass[208] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[78] clk n_282 VSS VSS VDD VDD pass[78] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[209] clk n_280 VSS VSS VDD VDD pass[209] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[79] clk n_279 VSS VSS VDD VDD pass[79] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[228] clk n_479 VSS VSS VDD VDD pass[228] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[80] clk n_276 VSS VSS VDD VDD pass[80] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[210] clk n_278 VSS VSS VDD VDD pass[210] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[211] clk n_275 VSS VSS VDD VDD pass[211] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[87] clk n_503 VSS VSS VDD VDD pass[87] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[212] clk n_274 VSS VSS VDD VDD pass[212] sky130_fd_sc_hd__dfxtp_1 
Xg4587 pass[255] VSS VSS VDD VDD out[255] sky130_fd_sc_hd__buf_8 
Xpass_reg[213] clk n_270 VSS VSS VDD VDD pass[213] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[223] clk n_509 VSS VSS VDD VDD pass[223] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[214] clk n_271 VSS VSS VDD VDD pass[214] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[215] clk n_269 VSS VSS VDD VDD pass[215] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[216] clk n_404 VSS VSS VDD VDD pass[216] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[15] clk n_267 VSS VSS VDD VDD pass[15] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[16] clk n_504 VSS VSS VDD VDD pass[16] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[82] clk n_266 VSS VSS VDD VDD pass[82] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[217] clk n_264 VSS VSS VDD VDD pass[217] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[83] clk n_263 VSS VSS VDD VDD pass[83] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[218] clk n_262 VSS VSS VDD VDD pass[218] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[219] clk n_261 VSS VSS VDD VDD pass[219] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[84] clk n_260 VSS VSS VDD VDD pass[84] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[220] clk n_322 VSS VSS VDD VDD pass[220] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[221] clk n_323 VSS VSS VDD VDD pass[221] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[222] clk n_289 VSS VSS VDD VDD pass[222] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[17] clk n_499 VSS VSS VDD VDD pass[17] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[85] clk n_258 VSS VSS VDD VDD pass[85] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[224] clk n_507 VSS VSS VDD VDD pass[224] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[86] clk n_508 VSS VSS VDD VDD pass[86] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[225] clk n_505 VSS VSS VDD VDD pass[225] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[3] clk n_417 VSS VSS VDD VDD pass[3] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[110] clk n_419 VSS VSS VDD VDD pass[110] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[88] clk n_494 VSS VSS VDD VDD pass[88] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[1] clk n_435 VSS VSS VDD VDD pass[1] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[19] clk n_490 VSS VSS VDD VDD pass[19] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[89] clk n_487 VSS VSS VDD VDD pass[89] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[229] clk n_493 VSS VSS VDD VDD pass[229] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[230] clk n_491 VSS VSS VDD VDD pass[230] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[231] clk n_488 VSS VSS VDD VDD pass[231] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[232] clk n_506 VSS VSS VDD VDD pass[232] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[233] clk n_484 VSS VSS VDD VDD pass[233] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[91] clk n_481 VSS VSS VDD VDD pass[91] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[234] clk n_265 VSS VSS VDD VDD pass[234] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[20] clk n_482 VSS VSS VDD VDD pass[20] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[92] clk n_476 VSS VSS VDD VDD pass[92] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[236] clk n_277 VSS VSS VDD VDD pass[236] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[238] clk n_473 VSS VSS VDD VDD pass[238] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[93] clk n_474 VSS VSS VDD VDD pass[93] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[239] clk n_470 VSS VSS VDD VDD pass[239] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[240] clk n_297 VSS VSS VDD VDD pass[240] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[94] clk n_467 VSS VSS VDD VDD pass[94] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[241] clk n_466 VSS VSS VDD VDD pass[241] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[2] clk n_501 VSS VSS VDD VDD pass[2] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[95] clk n_464 VSS VSS VDD VDD pass[95] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[242] clk n_303 VSS VSS VDD VDD pass[242] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[243] clk n_462 VSS VSS VDD VDD pass[243] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[244] clk n_460 VSS VSS VDD VDD pass[244] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[97] clk n_458 VSS VSS VDD VDD pass[97] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[245] clk n_459 VSS VSS VDD VDD pass[245] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[247] clk n_455 VSS VSS VDD VDD pass[247] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[248] clk n_375 VSS VSS VDD VDD pass[248] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[12] clk n_288 VSS VSS VDD VDD pass[12] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[98] clk n_393 VSS VSS VDD VDD pass[98] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[249] clk n_450 VSS VSS VDD VDD pass[249] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[99] clk n_446 VSS VSS VDD VDD pass[99] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[250] clk n_409 VSS VSS VDD VDD pass[250] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[18] clk n_497 VSS VSS VDD VDD pass[18] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[100] clk n_443 VSS VSS VDD VDD pass[100] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[252] clk n_444 VSS VSS VDD VDD pass[252] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[24] clk n_449 VSS VSS VDD VDD pass[24] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[253] clk n_442 VSS VSS VDD VDD pass[253] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[81] clk n_272 VSS VSS VDD VDD pass[81] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[26] clk n_433 VSS VSS VDD VDD pass[26] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[27] clk n_428 VSS VSS VDD VDD pass[27] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[101] clk n_440 VSS VSS VDD VDD pass[101] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[102] clk n_438 VSS VSS VDD VDD pass[102] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[103] clk n_436 VSS VSS VDD VDD pass[103] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[104] clk n_434 VSS VSS VDD VDD pass[104] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[105] clk n_431 VSS VSS VDD VDD pass[105] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[107] clk n_427 VSS VSS VDD VDD pass[107] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[28] clk n_426 VSS VSS VDD VDD pass[28] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[108] clk n_425 VSS VSS VDD VDD pass[108] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[227] clk n_498 VSS VSS VDD VDD pass[227] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[29] clk n_422 VSS VSS VDD VDD pass[29] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[111] clk n_418 VSS VSS VDD VDD pass[111] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[30] clk n_416 VSS VSS VDD VDD pass[30] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[113] clk n_414 VSS VSS VDD VDD pass[113] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[31] clk n_412 VSS VSS VDD VDD pass[31] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[32] clk n_408 VSS VSS VDD VDD pass[32] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[114] clk n_411 VSS VSS VDD VDD pass[114] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[115] clk n_410 VSS VSS VDD VDD pass[115] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[116] clk n_407 VSS VSS VDD VDD pass[116] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[117] clk n_403 VSS VSS VDD VDD pass[117] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[118] clk n_402 VSS VSS VDD VDD pass[118] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[119] clk n_401 VSS VSS VDD VDD pass[119] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[34] clk n_397 VSS VSS VDD VDD pass[34] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[35] clk n_391 VSS VSS VDD VDD pass[35] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[121] clk n_394 VSS VSS VDD VDD pass[121] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[123] clk n_390 VSS VSS VDD VDD pass[123] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[36] clk n_388 VSS VSS VDD VDD pass[36] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[124] clk n_386 VSS VSS VDD VDD pass[124] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[125] clk n_385 VSS VSS VDD VDD pass[125] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[126] clk n_382 VSS VSS VDD VDD pass[126] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[37] clk n_320 VSS VSS VDD VDD pass[37] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[38] clk n_368 VSS VSS VDD VDD pass[38] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[127] clk n_380 VSS VSS VDD VDD pass[127] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[128] clk n_379 VSS VSS VDD VDD pass[128] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[129] clk n_377 VSS VSS VDD VDD pass[129] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[130] clk n_374 VSS VSS VDD VDD pass[130] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[131] clk n_371 VSS VSS VDD VDD pass[131] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[132] clk n_370 VSS VSS VDD VDD pass[132] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[133] clk n_367 VSS VSS VDD VDD pass[133] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[134] clk n_366 VSS VSS VDD VDD pass[134] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[135] clk n_363 VSS VSS VDD VDD pass[135] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[136] clk n_360 VSS VSS VDD VDD pass[136] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[42] clk n_362 VSS VSS VDD VDD pass[42] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[137] clk n_359 VSS VSS VDD VDD pass[137] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[43] clk n_356 VSS VSS VDD VDD pass[43] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[139] clk n_354 VSS VSS VDD VDD pass[139] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[44] clk n_353 VSS VSS VDD VDD pass[44] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[45] clk n_340 VSS VSS VDD VDD pass[45] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[141] clk n_349 VSS VSS VDD VDD pass[141] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[142] clk n_347 VSS VSS VDD VDD pass[142] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[46] clk n_344 VSS VSS VDD VDD pass[46] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[144] clk n_343 VSS VSS VDD VDD pass[144] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[145] clk n_342 VSS VSS VDD VDD pass[145] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[47] clk n_338 VSS VSS VDD VDD pass[47] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[48] clk n_332 VSS VSS VDD VDD pass[48] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[146] clk n_337 VSS VSS VDD VDD pass[146] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[147] clk n_335 VSS VSS VDD VDD pass[147] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[148] clk n_334 VSS VSS VDD VDD pass[148] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[149] clk n_331 VSS VSS VDD VDD pass[149] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[150] clk n_330 VSS VSS VDD VDD pass[150] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[151] clk n_329 VSS VSS VDD VDD pass[151] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[23] clk n_451 VSS VSS VDD VDD pass[23] sky130_fd_sc_hd__dfxtp_1 
Xpass_reg[255] clk n_257 VSS VSS VDD VDD pass[255] sky130_fd_sc_hd__dfxtp_1 
Xg4609__5107 pass[165] n_914 pass[163] n_521 n_713 VSS VSS VDD VDD n_511 
+ sky130_fd_sc_hd__a221o_1 
Xg4718__6260 pass[224] n_853 pass[222] n_626 n_763 VSS VSS VDD VDD n_509 
+ sky130_fd_sc_hd__a221o_1 
Xg4719__4319 pass[87] n_872 pass[85] n_632 n_713 VSS VSS VDD VDD n_508 
+ sky130_fd_sc_hd__a221o_1 
Xg4720__8428 pass[225] n_923 pass[223] n_632 n_680 VSS VSS VDD VDD n_507 
+ sky130_fd_sc_hd__a221o_1 
Xg4721__5526 pass[233] n_853 pass[231] n_613 n_763 VSS VSS VDD VDD n_506 
+ sky130_fd_sc_hd__a221o_1 
Xg4722__6783 pass[226] n_800 pass[224] n_565 n_713 VSS VSS VDD VDD n_505 
+ sky130_fd_sc_hd__a221o_1 
Xg4589__3680 pass[17] n_866 pass[15] n_632 n_730 VSS VSS VDD VDD n_504 
+ sky130_fd_sc_hd__a221o_1 
Xg4723__1617 pass[88] n_805 pass[86] n_569 n_697 VSS VSS VDD VDD n_503 
+ sky130_fd_sc_hd__a221o_1 
Xg4590__2802 pass[205] n_862 pass[203] n_622 n_713 VSS VSS VDD VDD n_502 
+ sky130_fd_sc_hd__a221o_1 
Xg4591__1705 pass[3] n_800 pass[1] n_607 n_680 VSS VSS VDD VDD n_501 
+ sky130_fd_sc_hd__a221o_1 
Xg4724__5122 pass[227] n_853 pass[225] n_613 n_746 VSS VSS VDD VDD n_500 
+ sky130_fd_sc_hd__a221o_1 
Xg4725__8246 pass[18] n_800 pass[16] n_541 n_680 VSS VSS VDD VDD n_499 
+ sky130_fd_sc_hd__a221o_1 
Xg4726__7098 pass[228] n_897 pass[226] n_560 n_713 VSS VSS VDD VDD n_498 
+ sky130_fd_sc_hd__a221o_1 
Xg4727__6131 pass[19] n_923 pass[17] n_649 n_779 VSS VSS VDD VDD n_497 
+ sky130_fd_sc_hd__a221o_1 
Xg4592__1881 pass[154] n_914 pass[152] n_649 n_713 VSS VSS VDD VDD n_496 
+ sky130_fd_sc_hd__a221o_1 
Xg4593__5115 pass[155] n_889 pass[153] n_640 n_779 VSS VSS VDD VDD n_495 
+ sky130_fd_sc_hd__a221o_1 
Xg4728__7482 pass[89] n_796 pass[87] n_546 n_697 VSS VSS VDD VDD n_494 
+ sky130_fd_sc_hd__a221o_1 
Xg4729__4733 pass[230] n_862 pass[228] n_649 n_680 VSS VSS VDD VDD n_493 
+ sky130_fd_sc_hd__a221o_1 
Xg4594__6161 pass[52] n_800 pass[50] n_607 n_730 VSS VSS VDD VDD n_492 
+ sky130_fd_sc_hd__a221o_1 
Xg4730__9315 pass[231] n_889 pass[229] n_649 n_664 VSS VSS VDD VDD n_491 
+ sky130_fd_sc_hd__a221o_1 
Xg4731__9945 pass[20] n_838 pass[18] n_607 n_779 VSS VSS VDD VDD n_490 
+ sky130_fd_sc_hd__a221o_1 
Xg4595__2883 pass[156] n_857 pass[154] n_607 n_713 VSS VSS VDD VDD n_489 
+ sky130_fd_sc_hd__a221o_1 
Xg4732__2346 pass[232] n_838 pass[230] n_632 n_746 VSS VSS VDD VDD n_488 
+ sky130_fd_sc_hd__a221o_1 
Xg4733__1666 pass[90] n_805 pass[88] n_632 n_763 VSS VSS VDD VDD n_487 
+ sky130_fd_sc_hd__a221o_1 
Xg4734__7410 pass[91] n_857 pass[89] n_541 n_779 VSS VSS VDD VDD n_486 
+ sky130_fd_sc_hd__a221o_1 
Xg4596__6417 pass[53] n_914 pass[51] n_521 n_697 VSS VSS VDD VDD n_485 
+ sky130_fd_sc_hd__a221o_1 
Xg4735__5477 pass[234] n_923 pass[232] n_560 n_746 VSS VSS VDD VDD n_484 
+ sky130_fd_sc_hd__a221o_1 
Xg4597__2398 pass[157] n_914 pass[155] n_617 n_697 VSS VSS VDD VDD n_483 
+ sky130_fd_sc_hd__a221o_1 
Xg4736__5107 pass[21] n_796 pass[19] n_546 n_779 VSS VSS VDD VDD n_482 
+ sky130_fd_sc_hd__a221o_1 
Xg4737__6260 pass[92] n_866 pass[90] n_617 n_779 VSS VSS VDD VDD n_481 
+ sky130_fd_sc_hd__a221o_1 
Xg4598__4319 pass[158] n_838 pass[156] n_649 n_730 VSS VSS VDD VDD n_480 
+ sky130_fd_sc_hd__a221o_1 
Xg4738__8428 pass[229] n_857 pass[227] n_521 n_730 VSS VSS VDD VDD n_479 
+ sky130_fd_sc_hd__a221o_1 
Xg4739__5526 pass[236] n_834 pass[234] n_565 n_763 VSS VSS VDD VDD n_478 
+ sky130_fd_sc_hd__a221o_1 
Xg4599__6783 pass[54] n_923 pass[52] n_584 n_697 VSS VSS VDD VDD n_477 
+ sky130_fd_sc_hd__a221o_1 
Xg4740__3680 pass[93] n_843 pass[91] n_575 n_680 VSS VSS VDD VDD n_476 
+ sky130_fd_sc_hd__a221o_1 
Xg4741__1617 pass[238] n_914 pass[236] n_649 n_746 VSS VSS VDD VDD n_475 
+ sky130_fd_sc_hd__a221o_1 
Xg4742__2802 pass[94] n_847 pass[92] n_649 n_697 VSS VSS VDD VDD n_474 
+ sky130_fd_sc_hd__a221o_1 
Xg4743__1705 pass[239] n_906 pass[237] n_613 n_664 VSS VSS VDD VDD n_473 
+ sky130_fd_sc_hd__a221o_1 
Xg4600__5122 pass[159] n_847 pass[157] n_640 n_680 VSS VSS VDD VDD n_472 
+ sky130_fd_sc_hd__a221o_1 
Xg4601__8246 pass[160] n_809 pass[158] n_603 n_697 VSS VSS VDD VDD n_471 
+ sky130_fd_sc_hd__a221o_1 
Xg4744__7098 pass[240] n_906 pass[238] n_526 n_713 VSS VSS VDD VDD n_470 
+ sky130_fd_sc_hd__a221o_1 
Xg4745__6131 pass[22] n_847 pass[20] n_603 n_664 VSS VSS VDD VDD n_469 
+ sky130_fd_sc_hd__a221o_1 
Xg4602__1881 pass[161] n_872 pass[159] n_640 n_779 VSS VSS VDD VDD n_468 
+ sky130_fd_sc_hd__a221o_1 
Xg4746__5115 pass[95] n_847 pass[93] n_607 n_730 VSS VSS VDD VDD n_467 
+ sky130_fd_sc_hd__a221o_1 
Xg4747__7482 pass[242] n_834 pass[240] n_607 n_779 VSS VSS VDD VDD n_466 
+ sky130_fd_sc_hd__a221o_1 
Xg4603__4733 pass[162] n_906 pass[160] n_626 n_680 VSS VSS VDD VDD n_465 
+ sky130_fd_sc_hd__a221o_1 
Xg4748__6161 pass[96] n_809 pass[94] n_632 n_746 VSS VSS VDD VDD n_464 
+ sky130_fd_sc_hd__a221o_1 
Xg4749__9315 pass[97] n_906 pass[95] n_517 n_746 VSS VSS VDD VDD n_463 
+ sky130_fd_sc_hd__a221o_1 
Xg4750__9945 pass[244] n_906 pass[242] n_575 n_763 VSS VSS VDD VDD n_462 
+ sky130_fd_sc_hd__a221o_1 
Xg4605__2883 pass[56] n_897 pass[54] n_649 n_730 VSS VSS VDD VDD n_461 
+ sky130_fd_sc_hd__a221o_1 
Xg4751__2346 pass[245] n_843 pass[243] n_575 n_779 VSS VSS VDD VDD n_460 
+ sky130_fd_sc_hd__a221o_1 
Xg4752__1666 pass[246] n_897 pass[244] n_541 n_697 VSS VSS VDD VDD n_459 
+ sky130_fd_sc_hd__a221o_1 
Xg4753__7410 pass[98] n_923 pass[96] n_521 n_779 VSS VSS VDD VDD n_458 
+ sky130_fd_sc_hd__a221o_1 
Xg4606__6417 pass[163] n_843 pass[161] n_579 n_730 VSS VSS VDD VDD n_457 
+ sky130_fd_sc_hd__a221o_1 
Xg4754__5477 pass[247] n_824 pass[245] n_565 n_746 VSS VSS VDD VDD n_456 
+ sky130_fd_sc_hd__a221o_1 
Xg4755__2398 pass[248] n_889 pass[246] n_588 n_779 VSS VSS VDD VDD n_455 
+ sky130_fd_sc_hd__a221o_1 
Xg4604__5107 pass[55] n_897 pass[53] n_617 n_746 VSS VSS VDD VDD n_454 
+ sky130_fd_sc_hd__a221o_1 
Xg4607__6260 pass[57] n_872 pass[55] n_550 n_713 VSS VSS VDD VDD n_453 
+ sky130_fd_sc_hd__a221o_1 
Xg4756__4319 pass[23] n_889 pass[21] n_546 n_779 VSS VSS VDD VDD n_452 
+ sky130_fd_sc_hd__a221o_1 
Xg4757__8428 pass[24] n_897 pass[22] n_550 n_730 VSS VSS VDD VDD n_451 
+ sky130_fd_sc_hd__a221o_1 
Xg4758__5526 pass[250] n_843 pass[248] n_550 n_779 VSS VSS VDD VDD n_450 
+ sky130_fd_sc_hd__a221o_1 
Xg4759__6783 pass[25] n_914 pass[23] n_560 n_730 VSS VSS VDD VDD n_449 
+ sky130_fd_sc_hd__a221o_1 
Xg4608__3680 pass[164] n_824 pass[162] n_569 n_763 VSS VSS VDD VDD n_448 
+ sky130_fd_sc_hd__a221o_1 
Xg4588__1617 pass[186] n_809 pass[184] n_617 n_763 VSS VSS VDD VDD n_447 
+ sky130_fd_sc_hd__a221o_1 
Xg4760__2802 pass[100] n_828 pass[98] n_594 n_746 VSS VSS VDD VDD n_446 
+ sky130_fd_sc_hd__a221o_1 
Xg4761__1705 pass[252] n_880 pass[250] n_537 n_746 VSS VSS VDD VDD n_445 
+ sky130_fd_sc_hd__a221o_1 
Xg4610__5122 pass[253] n_880 pass[251] n_588 n_779 VSS VSS VDD VDD n_444 
+ sky130_fd_sc_hd__a221o_1 
Xg4762__8246 pass[101] n_880 pass[99] n_560 n_697 VSS VSS VDD VDD n_443 
+ sky130_fd_sc_hd__a221o_1 
Xg4763__7098 pass[254] n_815 pass[252] n_588 n_713 VSS VSS VDD VDD n_442 
+ sky130_fd_sc_hd__a221o_1 
Xg4611__6131 pass[166] n_923 pass[164] n_584 n_697 VSS VSS VDD VDD n_441 
+ sky130_fd_sc_hd__a221o_1 
Xg4764__1881 pass[102] n_815 pass[100] n_541 n_763 VSS VSS VDD VDD n_440 
+ sky130_fd_sc_hd__a221o_1 
Xg4765__5115 pass[26] n_819 pass[24] n_541 n_746 VSS VSS VDD VDD n_439 
+ sky130_fd_sc_hd__a221o_1 
Xg4766__7482 pass[103] n_923 pass[101] n_584 n_680 VSS VSS VDD VDD n_438 
+ sky130_fd_sc_hd__a221o_1 
Xg4612__4733 pass[167] n_819 pass[165] n_517 n_746 VSS VSS VDD VDD n_437 
+ sky130_fd_sc_hd__a221o_1 
Xg4767__6161 pass[104] n_815 pass[102] n_649 n_730 VSS VSS VDD VDD n_436 
+ sky130_fd_sc_hd__a221o_1 
Xg4613__9315 pass[2] n_819 pass[0] n_598 n_763 VSS VSS VDD VDD n_435 
+ sky130_fd_sc_hd__a221o_1 
Xg4768__9945 pass[105] n_828 pass[103] n_556 n_746 VSS VSS VDD VDD n_434 
+ sky130_fd_sc_hd__a221o_1 
Xg4769__2883 pass[27] n_880 pass[25] n_640 n_746 VSS VSS VDD VDD n_433 
+ sky130_fd_sc_hd__a221o_1 
Xg4614__2346 pass[168] n_819 pass[166] n_640 n_680 VSS VSS VDD VDD n_432 
+ sky130_fd_sc_hd__a221o_1 
Xg4770__1666 pass[106] n_923 pass[104] n_530 n_697 VSS VSS VDD VDD n_431 
+ sky130_fd_sc_hd__a221o_1 
Xg4771__7410 pass[107] n_880 pass[105] n_530 n_664 VSS VSS VDD VDD n_430 
+ sky130_fd_sc_hd__a221o_1 
Xg4615__6417 pass[58] n_923 pass[56] n_603 n_697 VSS VSS VDD VDD n_429 
+ sky130_fd_sc_hd__a221o_1 
Xg4772__5477 pass[28] n_815 pass[26] n_649 n_664 VSS VSS VDD VDD n_428 
+ sky130_fd_sc_hd__a221o_1 
Xg4773__2398 pass[108] n_880 pass[106] n_649 n_713 VSS VSS VDD VDD n_427 
+ sky130_fd_sc_hd__a221o_1 
Xg4774__5107 pass[29] n_880 pass[27] n_530 n_664 VSS VSS VDD VDD n_426 
+ sky130_fd_sc_hd__a221o_1 
Xg4775__6260 pass[109] n_824 pass[107] n_530 n_680 VSS VSS VDD VDD n_425 
+ sky130_fd_sc_hd__a221o_1 
Xg4616__4319 pass[59] n_880 pass[57] n_640 n_680 VSS VSS VDD VDD n_424 
+ sky130_fd_sc_hd__a221o_1 
Xg4617__8428 pass[169] n_923 pass[167] n_607 n_680 VSS VSS VDD VDD n_423 
+ sky130_fd_sc_hd__a221o_1 
Xg4776__5526 pass[30] n_880 pass[28] n_632 n_730 VSS VSS VDD VDD n_422 
+ sky130_fd_sc_hd__a221o_1 
Xg4777__6783 pass[110] n_828 pass[108] n_632 n_713 VSS VSS VDD VDD n_421 
+ sky130_fd_sc_hd__a221o_1 
Xg4618__3680 pass[170] n_819 pass[168] n_622 n_779 VSS VSS VDD VDD n_420 
+ sky130_fd_sc_hd__a221o_1 
Xg4778__1617 pass[111] n_923 pass[109] n_622 n_680 VSS VSS VDD VDD n_419 
+ sky130_fd_sc_hd__a221o_1 
Xg4779__2802 pass[112] n_815 pass[110] n_626 n_664 VSS VSS VDD VDD n_418 
+ sky130_fd_sc_hd__a221o_1 
Xg4619__1705 pass[4] n_923 pass[2] n_626 n_664 VSS VSS VDD VDD n_417 
+ sky130_fd_sc_hd__a221o_1 
Xg4780__5122 pass[31] n_809 pass[29] n_598 n_746 VSS VSS VDD VDD n_416 
+ sky130_fd_sc_hd__a221o_1 
Xg4781__8246 pass[113] n_824 pass[111] n_598 n_746 VSS VSS VDD VDD n_415 
+ sky130_fd_sc_hd__a221o_1 
Xg4782__7098 pass[114] n_843 pass[112] n_517 n_730 VSS VSS VDD VDD n_414 
+ sky130_fd_sc_hd__a221o_1 
Xg4621__6131 pass[171] n_897 pass[169] n_632 n_730 VSS VSS VDD VDD n_413 
+ sky130_fd_sc_hd__a221o_1 
Xg4783__1881 pass[32] n_897 pass[30] n_575 n_746 VSS VSS VDD VDD n_412 
+ sky130_fd_sc_hd__a221o_1 
Xg4784__5115 pass[115] n_889 pass[113] n_649 n_746 VSS VSS VDD VDD n_411 
+ sky130_fd_sc_hd__a221o_1 
Xg4785__7482 pass[116] n_843 pass[114] n_598 n_730 VSS VSS VDD VDD n_410 
+ sky130_fd_sc_hd__a221o_1 
Xg4622__4733 pass[251] n_923 pass[249] n_598 n_680 VSS VSS VDD VDD n_409 
+ sky130_fd_sc_hd__a221o_1 
Xg4786__6161 pass[33] n_906 pass[31] n_575 n_680 VSS VSS VDD VDD n_408 
+ sky130_fd_sc_hd__a221o_1 
Xg4787__9315 pass[117] n_906 pass[115] n_541 n_680 VSS VSS VDD VDD n_407 
+ sky130_fd_sc_hd__a221o_1 
Xg4620__9945 pass[60] n_906 pass[58] n_579 n_697 VSS VSS VDD VDD n_406 
+ sky130_fd_sc_hd__a221o_1 
Xg4623__2883 pass[172] n_834 pass[170] n_579 n_697 VSS VSS VDD VDD n_405 
+ sky130_fd_sc_hd__a221o_1 
Xg4788__2346 pass[217] n_847 pass[215] n_517 n_779 VSS VSS VDD VDD n_404 
+ sky130_fd_sc_hd__a221o_1 
Xg4789__1666 pass[118] n_906 pass[116] n_517 n_730 VSS VSS VDD VDD n_403 
+ sky130_fd_sc_hd__a221o_1 
Xg4790__7410 pass[119] n_847 pass[117] n_579 n_779 VSS VSS VDD VDD n_402 
+ sky130_fd_sc_hd__a221o_1 
Xg4791__6417 pass[120] n_906 pass[118] n_565 n_779 VSS VSS VDD VDD n_401 
+ sky130_fd_sc_hd__a221o_1 
Xg4624__5477 pass[5] n_834 pass[3] n_565 n_763 VSS VSS VDD VDD n_400 
+ sky130_fd_sc_hd__a221o_1 
Xg4625__2398 pass[61] n_857 pass[59] n_588 n_763 VSS VSS VDD VDD n_399 
+ sky130_fd_sc_hd__a221o_1 
Xg4792__5107 pass[34] n_866 pass[32] n_537 n_779 VSS VSS VDD VDD n_398 
+ sky130_fd_sc_hd__a221o_1 
Xg4793__6260 pass[35] n_796 pass[33] n_537 n_697 VSS VSS VDD VDD n_397 
+ sky130_fd_sc_hd__a221o_1 
Xg4626__4319 pass[173] n_914 pass[171] n_613 n_746 VSS VSS VDD VDD n_396 
+ sky130_fd_sc_hd__a221o_1 
Xg4794__8428 pass[121] n_857 pass[119] n_613 n_713 VSS VSS VDD VDD n_395 
+ sky130_fd_sc_hd__a221o_1 
Xg4795__5526 pass[122] n_838 pass[120] n_550 n_697 VSS VSS VDD VDD n_394 
+ sky130_fd_sc_hd__a221o_1 
Xg4627__6783 pass[99] n_857 pass[97] n_649 n_697 VSS VSS VDD VDD n_393 
+ sky130_fd_sc_hd__a221o_1 
Xg4796__3680 pass[123] n_862 pass[121] n_537 n_779 VSS VSS VDD VDD n_392 
+ sky130_fd_sc_hd__a221o_1 
Xg4797__1617 pass[36] n_796 pass[34] n_537 n_730 VSS VSS VDD VDD n_391 
+ sky130_fd_sc_hd__a221o_1 
Xg4798__2802 pass[124] n_914 pass[122] n_550 n_730 VSS VSS VDD VDD n_390 
+ sky130_fd_sc_hd__a221o_1 
Xg4628__1705 pass[197] n_923 pass[195] n_617 n_730 VSS VSS VDD VDD n_389 
+ sky130_fd_sc_hd__a221o_1 
Xg4799__5122 pass[37] n_853 pass[35] n_550 n_779 VSS VSS VDD VDD n_388 
+ sky130_fd_sc_hd__a221o_1 
Xg4629__8246 pass[174] n_800 pass[172] n_560 n_779 VSS VSS VDD VDD n_387 
+ sky130_fd_sc_hd__a221o_1 
Xg4800__7098 pass[125] n_805 pass[123] n_632 n_730 VSS VSS VDD VDD n_386 
+ sky130_fd_sc_hd__a221o_1 
Xg4801__6131 pass[126] n_866 pass[124] n_632 n_779 VSS VSS VDD VDD n_385 
+ sky130_fd_sc_hd__a221o_1 
Xg4630__1881 pass[62] n_872 pass[60] n_594 n_763 VSS VSS VDD VDD n_384 
+ sky130_fd_sc_hd__a221o_1 
Xg4654__5115 pass[187] n_872 pass[185] n_560 n_730 VSS VSS VDD VDD n_383 
+ sky130_fd_sc_hd__a221o_1 
Xg4803__7482 pass[127] n_906 pass[125] n_613 n_763 VSS VSS VDD VDD n_382 
+ sky130_fd_sc_hd__a221o_1 
Xg4631__4733 pass[175] n_923 pass[173] n_594 n_697 VSS VSS VDD VDD n_381 
+ sky130_fd_sc_hd__a221o_1 
Xg4804__6161 pass[128] n_923 pass[126] n_550 n_730 VSS VSS VDD VDD n_380 
+ sky130_fd_sc_hd__a221o_1 
Xg4805__9315 pass[129] n_897 pass[127] n_521 n_713 VSS VSS VDD VDD n_379 
+ sky130_fd_sc_hd__a221o_1 
Xg4806__9945 pass[40] n_914 pass[38] n_537 n_763 VSS VSS VDD VDD n_378 
+ sky130_fd_sc_hd__a221o_1 
Xg4807__2883 pass[130] n_914 pass[128] n_594 n_730 VSS VSS VDD VDD n_377 
+ sky130_fd_sc_hd__a221o_1 
Xg4632__2346 pass[176] n_923 pass[174] n_546 n_763 VSS VSS VDD VDD n_376 
+ sky130_fd_sc_hd__a221o_1 
Xg4633__1666 pass[249] n_805 pass[247] n_565 n_779 VSS VSS VDD VDD n_375 
+ sky130_fd_sc_hd__a221o_1 
Xg4808__7410 pass[131] n_853 pass[129] n_569 n_713 VSS VSS VDD VDD n_374 
+ sky130_fd_sc_hd__a221o_1 
Xg4809__6417 pass[41] n_853 pass[39] n_588 n_746 VSS VSS VDD VDD n_373 
+ sky130_fd_sc_hd__a221o_1 
Xg4634__5477 pass[6] n_897 pass[4] n_579 n_746 VSS VSS VDD VDD n_372 
+ sky130_fd_sc_hd__a221o_1 
Xg4810__2398 pass[132] n_897 pass[130] n_640 n_713 VSS VSS VDD VDD n_371 
+ sky130_fd_sc_hd__a221o_1 
Xg4811__5107 pass[133] n_889 pass[131] n_569 n_713 VSS VSS VDD VDD n_370 
+ sky130_fd_sc_hd__a221o_1 
Xg4635__6260 pass[63] n_796 pass[61] n_579 n_763 VSS VSS VDD VDD n_369 
+ sky130_fd_sc_hd__a221o_1 
Xg4812__4319 pass[39] n_796 pass[37] n_556 n_680 VSS VSS VDD VDD n_368 
+ sky130_fd_sc_hd__a221o_1 
Xg4813__8428 pass[134] n_889 pass[132] n_575 n_763 VSS VSS VDD VDD n_367 
+ sky130_fd_sc_hd__a221o_1 
Xg4814__5526 pass[135] n_906 pass[133] n_517 n_779 VSS VSS VDD VDD n_366 
+ sky130_fd_sc_hd__a221o_1 
Xg4637__6783 pass[178] n_906 pass[176] n_584 n_713 VSS VSS VDD VDD n_365 
+ sky130_fd_sc_hd__a221o_1 
Xg4815__3680 pass[42] n_805 pass[40] n_649 n_713 VSS VSS VDD VDD n_364 
+ sky130_fd_sc_hd__a221o_1 
Xg4816__1617 pass[136] n_805 pass[134] n_649 n_746 VSS VSS VDD VDD n_363 
+ sky130_fd_sc_hd__a221o_1 
Xg4817__2802 pass[43] n_857 pass[41] n_632 n_697 VSS VSS VDD VDD n_362 
+ sky130_fd_sc_hd__a221o_1 
Xg4638__1705 pass[64] n_834 pass[62] n_556 n_680 VSS VSS VDD VDD n_361 
+ sky130_fd_sc_hd__a221o_1 
Xg4818__5122 pass[137] n_834 pass[135] n_649 n_680 VSS VSS VDD VDD n_360 
+ sky130_fd_sc_hd__a221o_1 
Xg4819__8246 pass[138] n_834 pass[136] n_598 n_763 VSS VSS VDD VDD n_359 
+ sky130_fd_sc_hd__a221o_1 
Xg4636__7098 pass[177] n_914 pass[175] n_556 n_730 VSS VSS VDD VDD n_358 
+ sky130_fd_sc_hd__a221o_1 
Xg4639__6131 pass[179] n_872 pass[177] n_632 n_664 VSS VSS VDD VDD n_357 
+ sky130_fd_sc_hd__a221o_1 
Xg4820__1881 pass[44] n_838 pass[42] n_626 n_763 VSS VSS VDD VDD n_356 
+ sky130_fd_sc_hd__a221o_1 
Xg4821__5115 pass[139] n_872 pass[137] n_546 n_664 VSS VSS VDD VDD n_355 
+ sky130_fd_sc_hd__a221o_1 
Xg4822__7482 pass[140] n_897 pass[138] n_640 n_763 VSS VSS VDD VDD n_354 
+ sky130_fd_sc_hd__a221o_1 
Xg4823__4733 pass[45] n_897 pass[43] n_617 n_664 VSS VSS VDD VDD n_353 
+ sky130_fd_sc_hd__a221o_1 
Xg4640__6161 pass[65] n_923 pass[63] n_640 n_664 VSS VSS VDD VDD n_352 
+ sky130_fd_sc_hd__a221o_1 
Xg4641__9315 pass[180] n_824 pass[178] n_622 n_664 VSS VSS VDD VDD n_351 
+ sky130_fd_sc_hd__a221o_1 
Xg4824__9945 pass[141] n_880 pass[139] n_526 n_664 VSS VSS VDD VDD n_350 
+ sky130_fd_sc_hd__a221o_1 
Xg4825__2883 pass[142] n_880 pass[140] n_530 n_664 VSS VSS VDD VDD n_349 
+ sky130_fd_sc_hd__a221o_1 
Xg4642__2346 pass[181] n_872 pass[179] n_603 n_680 VSS VSS VDD VDD n_348 
+ sky130_fd_sc_hd__a221o_1 
Xg4826__1666 pass[143] n_872 pass[141] n_526 n_697 VSS VSS VDD VDD n_347 
+ sky130_fd_sc_hd__a221o_1 
Xg4827__7410 pass[144] n_809 pass[142] n_649 n_664 VSS VSS VDD VDD n_346 
+ sky130_fd_sc_hd__a221o_1 
Xg4643__6417 pass[7] n_828 pass[5] n_626 n_664 VSS VSS VDD VDD n_345 
+ sky130_fd_sc_hd__a221o_1 
Xg4828__5477 pass[47] n_828 pass[45] n_622 n_680 VSS VSS VDD VDD n_344 
+ sky130_fd_sc_hd__a221o_1 
Xg4829__2398 pass[145] n_828 pass[143] n_526 n_713 VSS VSS VDD VDD n_343 
+ sky130_fd_sc_hd__a221o_1 
Xg4830__5107 pass[146] n_880 pass[144] n_649 n_664 VSS VSS VDD VDD n_342 
+ sky130_fd_sc_hd__a221o_1 
Xg4644__6260 pass[182] n_824 pass[180] n_603 n_664 VSS VSS VDD VDD n_341 
+ sky130_fd_sc_hd__a221o_1 
Xg4831__4319 pass[46] n_819 pass[44] n_526 n_680 VSS VSS VDD VDD n_340 
+ sky130_fd_sc_hd__a221o_1 
Xg4645__8428 pass[66] n_819 pass[64] n_622 n_664 VSS VSS VDD VDD n_339 
+ sky130_fd_sc_hd__a221o_1 
Xg4832__5526 pass[48] n_819 pass[46] n_649 n_713 VSS VSS VDD VDD n_338 
+ sky130_fd_sc_hd__a221o_1 
Xg4833__6783 pass[147] n_815 pass[145] n_526 n_664 VSS VSS VDD VDD n_337 
+ sky130_fd_sc_hd__a221o_1 
Xg4646__3680 pass[183] n_914 pass[181] n_649 n_664 VSS VSS VDD VDD n_336 
+ sky130_fd_sc_hd__a221o_1 
Xg4834__1617 pass[148] n_889 pass[146] n_626 n_664 VSS VSS VDD VDD n_335 
+ sky130_fd_sc_hd__a221o_1 
Xg4835__2802 pass[149] n_824 pass[147] n_649 n_697 VSS VSS VDD VDD n_334 
+ sky130_fd_sc_hd__a221o_1 
Xg4647__1705 pass[184] n_897 pass[182] n_603 n_697 VSS VSS VDD VDD n_333 
+ sky130_fd_sc_hd__a221o_1 
Xg4836__5122 pass[49] n_809 pass[47] n_526 n_680 VSS VSS VDD VDD n_332 
+ sky130_fd_sc_hd__a221o_1 
Xg4837__8246 pass[150] n_847 pass[148] n_603 n_664 VSS VSS VDD VDD n_331 
+ sky130_fd_sc_hd__a221o_1 
Xg4838__7098 pass[151] n_809 pass[149] n_530 n_697 VSS VSS VDD VDD n_330 
+ sky130_fd_sc_hd__a221o_1 
Xg4839__6131 pass[152] n_847 pass[150] n_603 n_664 VSS VSS VDD VDD n_329 
+ sky130_fd_sc_hd__a221o_1 
Xg4648__1881 pass[8] n_838 pass[6] n_530 n_664 VSS VSS VDD VDD n_328 
+ sky130_fd_sc_hd__a221o_1 
Xg4649__5115 pass[67] n_914 pass[65] n_526 n_697 VSS VSS VDD VDD n_327 
+ sky130_fd_sc_hd__a221o_1 
Xg4840__7482 pass[50] n_805 pass[48] n_530 n_664 VSS VSS VDD VDD n_326 
+ sky130_fd_sc_hd__a221o_1 
Xg4841__4733 pass[51] n_838 pass[49] n_622 n_664 VSS VSS VDD VDD n_325 
+ sky130_fd_sc_hd__a221o_1 
Xg4650__6161 pass[185] n_889 pass[183] n_640 n_680 VSS VSS VDD VDD n_324 
+ sky130_fd_sc_hd__a221o_1 
Xg4842__9315 pass[222] n_897 pass[220] n_640 n_680 VSS VSS VDD VDD n_323 
+ sky130_fd_sc_hd__a221o_1 
Xg4651__9945 pass[221] n_862 pass[219] n_640 n_730 VSS VSS VDD VDD n_322 
+ sky130_fd_sc_hd__a221o_1 
Xg4653__2883 pass[68] n_800 pass[66] n_607 n_713 VSS VSS VDD VDD n_321 
+ sky130_fd_sc_hd__a221o_1 
Xg4802__2346 pass[38] n_906 pass[36] n_622 n_680 VSS VSS VDD VDD n_320 
+ sky130_fd_sc_hd__a221o_1 
Xg4652__1666 pass[9] n_923 pass[7] n_632 n_664 VSS VSS VDD VDD n_319 
+ sky130_fd_sc_hd__a221o_1 
Xg4655__7410 pass[188] n_897 pass[186] n_617 n_763 VSS VSS VDD VDD n_318 
+ sky130_fd_sc_hd__a221o_1 
Xg4656__6417 pass[69] n_923 pass[67] n_640 n_746 VSS VSS VDD VDD n_317 
+ sky130_fd_sc_hd__a221o_1 
Xg4657__5477 pass[189] n_805 pass[187] n_640 n_664 VSS VSS VDD VDD n_316 
+ sky130_fd_sc_hd__a221o_1 
Xg4658__2398 pass[190] n_889 pass[188] n_546 n_763 VSS VSS VDD VDD n_315 
+ sky130_fd_sc_hd__a221o_1 
Xg4659__5107 pass[70] n_889 pass[68] n_626 n_746 VSS VSS VDD VDD n_314 
+ sky130_fd_sc_hd__a221o_1 
Xg4660__6260 pass[191] n_796 pass[189] n_556 n_664 VSS VSS VDD VDD n_313 
+ sky130_fd_sc_hd__a221o_1 
Xg4661__4319 pass[192] n_889 pass[190] n_613 n_664 VSS VSS VDD VDD n_312 
+ sky130_fd_sc_hd__a221o_1 
Xg4662__8428 pass[71] n_862 pass[69] n_632 n_730 VSS VSS VDD VDD n_311 
+ sky130_fd_sc_hd__a221o_1 
Xg4663__5526 pass[193] n_857 pass[191] n_556 n_763 VSS VSS VDD VDD n_310 
+ sky130_fd_sc_hd__a221o_1 
Xg4664__6783 pass[194] n_834 pass[192] n_598 n_763 VSS VSS VDD VDD n_309 
+ sky130_fd_sc_hd__a221o_1 
Xg4665__3680 pass[10] n_914 pass[8] n_598 n_680 VSS VSS VDD VDD n_308 
+ sky130_fd_sc_hd__a221o_1 
Xg4666__1617 pass[72] n_872 pass[70] n_649 n_730 VSS VSS VDD VDD n_307 
+ sky130_fd_sc_hd__a221o_1 
Xg4667__2802 pass[195] n_872 pass[193] n_649 n_697 VSS VSS VDD VDD n_306 
+ sky130_fd_sc_hd__a221o_1 
Xg4669__1705 pass[196] n_872 pass[194] n_649 n_680 VSS VSS VDD VDD n_305 
+ sky130_fd_sc_hd__a221o_1 
Xg4682__5122 pass[203] n_824 pass[201] n_649 n_680 VSS VSS VDD VDD n_304 
+ sky130_fd_sc_hd__a221o_1 
Xg4670__8246 pass[243] n_866 pass[241] n_556 n_697 VSS VSS VDD VDD n_303 
+ sky130_fd_sc_hd__a221o_1 
Xg4680__7098 pass[202] n_809 pass[200] n_632 n_746 VSS VSS VDD VDD n_302 
+ sky130_fd_sc_hd__a221o_1 
Xg4671__6131 pass[73] n_828 pass[71] n_517 n_746 VSS VSS VDD VDD n_301 
+ sky130_fd_sc_hd__a221o_1 
Xg4668__1881 pass[11] n_880 pass[9] n_649 n_713 VSS VSS VDD VDD n_300 
+ sky130_fd_sc_hd__a221o_1 
Xg4678__5115 pass[75] n_815 pass[73] n_649 n_680 VSS VSS VDD VDD n_299 
+ sky130_fd_sc_hd__a221o_1 
Xg4677__7482 pass[12] n_815 pass[10] n_584 n_746 VSS VSS VDD VDD n_298 
+ sky130_fd_sc_hd__a221o_1 
Xg4673__4733 pass[241] n_880 pass[239] n_649 n_713 VSS VSS VDD VDD n_297 
+ sky130_fd_sc_hd__a221o_1 
Xg4672__6161 pass[198] n_872 pass[196] n_584 n_779 VSS VSS VDD VDD n_296 
+ sky130_fd_sc_hd__a221o_1 
Xg4674__9315 pass[74] n_843 pass[72] n_517 n_746 VSS VSS VDD VDD n_295 
+ sky130_fd_sc_hd__a221o_1 
Xg4675__9945 pass[199] n_872 pass[197] n_541 n_763 VSS VSS VDD VDD n_294 
+ sky130_fd_sc_hd__a221o_1 
Xg4676__2883 pass[200] n_914 pass[198] n_575 n_680 VSS VSS VDD VDD n_293 
+ sky130_fd_sc_hd__a221o_1 
Xg4679__2346 pass[201] n_923 pass[199] n_556 n_763 VSS VSS VDD VDD n_292 
+ sky130_fd_sc_hd__a221o_1 
Xg4681__1666 pass[76] n_889 pass[74] n_541 n_680 VSS VSS VDD VDD n_291 
+ sky130_fd_sc_hd__a221o_1 
Xg4683__7410 pass[204] n_800 pass[202] n_575 n_697 VSS VSS VDD VDD n_290 
+ sky130_fd_sc_hd__a221o_1 
Xg4717__6417 pass[223] n_853 pass[221] n_546 n_697 VSS VSS VDD VDD n_289 
+ sky130_fd_sc_hd__a221o_1 
Xg4684__5477 pass[13] n_923 pass[11] n_569 n_763 VSS VSS VDD VDD n_288 
+ sky130_fd_sc_hd__a221o_1 
Xg4686__2398 pass[78] n_923 pass[76] n_579 n_713 VSS VSS VDD VDD n_287 
+ sky130_fd_sc_hd__a221o_1 
Xg4685__5107 pass[77] n_889 pass[75] n_569 n_697 VSS VSS VDD VDD n_286 
+ sky130_fd_sc_hd__a221o_1 
Xg4687__6260 pass[206] n_889 pass[204] n_584 n_713 VSS VSS VDD VDD n_285 
+ sky130_fd_sc_hd__a221o_1 
Xg4688__4319 pass[207] n_862 pass[205] n_640 n_746 VSS VSS VDD VDD n_284 
+ sky130_fd_sc_hd__a221o_1 
Xg4689__8428 pass[208] n_862 pass[206] n_579 n_713 VSS VSS VDD VDD n_283 
+ sky130_fd_sc_hd__a221o_1 
Xg4690__5526 pass[79] n_838 pass[77] n_588 n_697 VSS VSS VDD VDD n_282 
+ sky130_fd_sc_hd__a221o_1 
Xg4691__6783 pass[209] n_872 pass[207] n_584 n_746 VSS VSS VDD VDD n_281 
+ sky130_fd_sc_hd__a221o_1 
Xg4692__3680 pass[210] n_866 pass[208] n_588 n_713 VSS VSS VDD VDD n_280 
+ sky130_fd_sc_hd__a221o_1 
Xg4693__1617 pass[80] n_866 pass[78] n_569 n_697 VSS VSS VDD VDD n_279 
+ sky130_fd_sc_hd__a221o_1 
Xg4694__2802 pass[211] n_923 pass[209] n_560 n_779 VSS VSS VDD VDD n_278 
+ sky130_fd_sc_hd__a221o_1 
Xg4695__1705 pass[237] n_880 pass[235] n_565 n_763 VSS VSS VDD VDD n_277 
+ sky130_fd_sc_hd__a221o_1 
Xg4696__5122 pass[81] n_897 pass[79] n_546 n_779 VSS VSS VDD VDD n_276 
+ sky130_fd_sc_hd__a221o_1 
Xg4697__8246 pass[212] n_843 pass[210] n_588 n_763 VSS VSS VDD VDD n_275 
+ sky130_fd_sc_hd__a221o_1 
Xg4698__7098 pass[213] n_800 pass[211] n_565 n_779 VSS VSS VDD VDD n_274 
+ sky130_fd_sc_hd__a221o_1 
Xg4699__6131 pass[14] n_923 pass[12] n_640 n_730 VSS VSS VDD VDD n_273 
+ sky130_fd_sc_hd__a221o_1 
Xg4701__1881 pass[82] n_923 pass[80] n_594 n_763 VSS VSS VDD VDD n_272 
+ sky130_fd_sc_hd__a221o_1 
Xg4702__5115 pass[215] n_889 pass[213] n_537 n_746 VSS VSS VDD VDD n_271 
+ sky130_fd_sc_hd__a221o_1 
Xg4700__7482 pass[214] n_862 pass[212] n_537 n_713 VSS VSS VDD VDD n_270 
+ sky130_fd_sc_hd__a221o_1 
Xg4703__4733 pass[216] n_906 pass[214] n_521 n_730 VSS VSS VDD VDD n_269 
+ sky130_fd_sc_hd__a221o_1 
Xg4704__6161 pass[15] n_866 pass[13] n_550 n_746 VSS VSS VDD VDD n_268 
+ sky130_fd_sc_hd__a221o_1 
Xg4705__9315 pass[16] n_880 pass[14] n_594 n_730 VSS VSS VDD VDD n_267 
+ sky130_fd_sc_hd__a221o_1 
Xg4706__9945 pass[83] n_923 pass[81] n_521 n_697 VSS VSS VDD VDD n_266 
+ sky130_fd_sc_hd__a221o_1 
Xg4707__2883 pass[235] n_872 pass[233] n_594 n_763 VSS VSS VDD VDD n_265 
+ sky130_fd_sc_hd__a221o_1 
Xg4708__2346 pass[218] n_796 pass[216] n_613 n_763 VSS VSS VDD VDD n_264 
+ sky130_fd_sc_hd__a221o_1 
Xg4709__1666 pass[84] n_906 pass[82] n_617 n_730 VSS VSS VDD VDD n_263 
+ sky130_fd_sc_hd__a221o_1 
Xg4710__7410 pass[219] n_828 pass[217] n_560 n_779 VSS VSS VDD VDD n_262 
+ sky130_fd_sc_hd__a221o_1 
Xg4711__6417 pass[220] n_853 pass[218] n_536 n_730 VSS VSS VDD VDD n_261 
+ sky130_fd_sc_hd__a221o_1 
Xg4712__5477 pass[85] n_923 pass[83] n_594 n_713 VSS VSS VDD VDD n_260 
+ sky130_fd_sc_hd__a221o_1 
Xg4715__2398 pass[153] n_923 pass[151] n_569 n_730 VSS VSS VDD VDD n_259 
+ sky130_fd_sc_hd__a221o_1 
Xg4716__5107 pass[86] n_914 pass[84] n_649 n_779 VSS VSS VDD VDD n_258 
+ sky130_fd_sc_hd__a221o_1 
Xpass_reg[0] clk n_256 VSS VSS VDD VDD pass[0] sky130_fd_sc_hd__dfxtp_1 
Xg4843__6260 n_254 n_649 n_779 VSS VSS VDD VDD n_257 sky130_fd_sc_hd__a21o_1 
Xg4844__4319 n_536 n_713 pass[1] VSS VSS VDD VDD n_256 sky130_fd_sc_hd__or3_1 
Xg5012 n_254 VSS VSS VDD VDD out[254] sky130_fd_sc_hd__buf_8 
Xg4860 pass[143] VSS VSS VDD VDD out[143] sky130_fd_sc_hd__buf_8 
Xg5022 pass[96] VSS VSS VDD VDD out[96] sky130_fd_sc_hd__buf_8 
Xg4948 pass[108] VSS VSS VDD VDD out[108] sky130_fd_sc_hd__buf_8 
Xg5031 pass[166] VSS VSS VDD VDD out[166] sky130_fd_sc_hd__buf_8 
Xg5079 pass[127] VSS VSS VDD VDD out[127] sky130_fd_sc_hd__buf_8 
Xg5017 pass[158] VSS VSS VDD VDD out[158] sky130_fd_sc_hd__buf_8 
Xg4849 pass[3] VSS VSS VDD VDD out[3] sky130_fd_sc_hd__buf_8 
Xg5036 pass[184] VSS VSS VDD VDD out[184] sky130_fd_sc_hd__buf_8 
Xg4883 pass[246] VSS VSS VDD VDD out[246] sky130_fd_sc_hd__buf_8 
Xg5003 pass[215] VSS VSS VDD VDD out[215] sky130_fd_sc_hd__buf_8 
Xg4938 pass[193] VSS VSS VDD VDD out[193] sky130_fd_sc_hd__buf_8 
Xg4915 pass[189] VSS VSS VDD VDD out[189] sky130_fd_sc_hd__buf_8 
Xg4981 pass[110] VSS VSS VDD VDD out[110] sky130_fd_sc_hd__buf_8 
Xg5059 pass[214] VSS VSS VDD VDD out[214] sky130_fd_sc_hd__buf_8 
Xg5034 pass[183] VSS VSS VDD VDD out[183] sky130_fd_sc_hd__buf_8 
Xg4923 pass[165] VSS VSS VDD VDD out[165] sky130_fd_sc_hd__buf_8 
Xg4924 pass[172] VSS VSS VDD VDD out[172] sky130_fd_sc_hd__buf_8 
Xg5005 pass[51] VSS VSS VDD VDD out[51] sky130_fd_sc_hd__buf_8 
Xg5087 pass[37] VSS VSS VDD VDD out[37] sky130_fd_sc_hd__buf_8 
Xg4943 pass[126] VSS VSS VDD VDD out[126] sky130_fd_sc_hd__buf_8 
Xg5063 pass[202] VSS VSS VDD VDD out[202] sky130_fd_sc_hd__buf_8 
Xg5053 pass[38] VSS VSS VDD VDD out[38] sky130_fd_sc_hd__buf_8 
Xg5001 pass[122] VSS VSS VDD VDD out[122] sky130_fd_sc_hd__buf_8 
Xg4964 pass[216] VSS VSS VDD VDD out[216] sky130_fd_sc_hd__buf_8 
Xg4918 pass[121] VSS VSS VDD VDD out[121] sky130_fd_sc_hd__buf_8 
Xg4870 pass[15] VSS VSS VDD VDD out[15] sky130_fd_sc_hd__buf_8 
Xg4976 pass[212] VSS VSS VDD VDD out[212] sky130_fd_sc_hd__buf_8 
Xg4893 pass[170] VSS VSS VDD VDD out[170] sky130_fd_sc_hd__buf_8 
Xg4855 pass[34] VSS VSS VDD VDD out[34] sky130_fd_sc_hd__buf_8 
Xg4991 pass[211] VSS VSS VDD VDD out[211] sky130_fd_sc_hd__buf_8 
Xg5085 pass[210] VSS VSS VDD VDD out[210] sky130_fd_sc_hd__buf_8 
Xg5064 pass[118] VSS VSS VDD VDD out[118] sky130_fd_sc_hd__buf_8 
Xg4846 pass[117] VSS VSS VDD VDD out[117] sky130_fd_sc_hd__buf_8 
Xg4867 pass[197] VSS VSS VDD VDD out[197] sky130_fd_sc_hd__buf_8 
Xg5097 pass[79] VSS VSS VDD VDD out[79] sky130_fd_sc_hd__buf_8 
Xg4939 pass[115] VSS VSS VDD VDD out[115] sky130_fd_sc_hd__buf_8 
Xg4903 pass[234] VSS VSS VDD VDD out[234] sky130_fd_sc_hd__buf_8 
Xg4970 pass[114] VSS VSS VDD VDD out[114] sky130_fd_sc_hd__buf_8 
Xg4994 pass[209] VSS VSS VDD VDD out[209] sky130_fd_sc_hd__buf_8 
Xg5035 pass[32] VSS VSS VDD VDD out[32] sky130_fd_sc_hd__buf_8 
Xg4886 pass[31] VSS VSS VDD VDD out[31] sky130_fd_sc_hd__buf_8 
Xg4934 pass[78] VSS VSS VDD VDD out[78] sky130_fd_sc_hd__buf_8 
Xg4946 pass[30] VSS VSS VDD VDD out[30] sky130_fd_sc_hd__buf_8 
Xg5044 pass[91] VSS VSS VDD VDD out[91] sky130_fd_sc_hd__buf_8 
Xg4848 pass[208] VSS VSS VDD VDD out[208] sky130_fd_sc_hd__buf_8 
Xg4979 pass[112] VSS VSS VDD VDD out[112] sky130_fd_sc_hd__buf_8 
Xg5043 pass[111] VSS VSS VDD VDD out[111] sky130_fd_sc_hd__buf_8 
Xg4858 pass[207] VSS VSS VDD VDD out[207] sky130_fd_sc_hd__buf_8 
Xg5032 pass[227] VSS VSS VDD VDD out[227] sky130_fd_sc_hd__buf_8 
Xg4884 pass[5] VSS VSS VDD VDD out[5] sky130_fd_sc_hd__buf_8 
Xg5081 pass[160] VSS VSS VDD VDD out[160] sky130_fd_sc_hd__buf_8 
Xg5004 pass[178] VSS VSS VDD VDD out[178] sky130_fd_sc_hd__buf_8 
Xg5061 pass[248] VSS VSS VDD VDD out[248] sky130_fd_sc_hd__buf_8 
Xg5028 pass[14] VSS VSS VDD VDD out[14] sky130_fd_sc_hd__buf_8 
Xg5062 pass[175] VSS VSS VDD VDD out[175] sky130_fd_sc_hd__buf_8 
Xg5008 pass[192] VSS VSS VDD VDD out[192] sky130_fd_sc_hd__buf_8 
Xg4933 pass[252] VSS VSS VDD VDD out[252] sky130_fd_sc_hd__buf_8 
Xg5052 pass[171] VSS VSS VDD VDD out[171] sky130_fd_sc_hd__buf_8 
Xg4911 pass[243] VSS VSS VDD VDD out[243] sky130_fd_sc_hd__buf_8 
Xg4982 pass[27] VSS VSS VDD VDD out[27] sky130_fd_sc_hd__buf_8 
Xg4875 pass[12] VSS VSS VDD VDD out[12] sky130_fd_sc_hd__buf_8 
Xg4856 pass[163] VSS VSS VDD VDD out[163] sky130_fd_sc_hd__buf_8 
Xg4877 pass[76] VSS VSS VDD VDD out[76] sky130_fd_sc_hd__buf_8 
Xg4898 pass[63] VSS VSS VDD VDD out[63] sky130_fd_sc_hd__buf_8 
Xg4945 pass[102] VSS VSS VDD VDD out[102] sky130_fd_sc_hd__buf_8 
Xg4907 pass[100] VSS VSS VDD VDD out[100] sky130_fd_sc_hd__buf_8 
Xg4872 pass[233] VSS VSS VDD VDD out[233] sky130_fd_sc_hd__buf_8 
Xg5078 pass[98] VSS VSS VDD VDD out[98] sky130_fd_sc_hd__buf_8 
Xg4894 pass[62] VSS VSS VDD VDD out[62] sky130_fd_sc_hd__buf_8 
Xg5045 pass[164] VSS VSS VDD VDD out[164] sky130_fd_sc_hd__buf_8 
Xg4862 pass[70] VSS VSS VDD VDD out[70] sky130_fd_sc_hd__buf_8 
Xg4892 pass[50] VSS VSS VDD VDD out[50] sky130_fd_sc_hd__buf_8 
Xg5075 pass[104] VSS VSS VDD VDD out[104] sky130_fd_sc_hd__buf_8 
Xg4932 pass[74] VSS VSS VDD VDD out[74] sky130_fd_sc_hd__buf_8 
Xg5007 pass[204] VSS VSS VDD VDD out[204] sky130_fd_sc_hd__buf_8 
Xg4902 pass[55] VSS VSS VDD VDD out[55] sky130_fd_sc_hd__buf_8 
Xg4962 pass[174] VSS VSS VDD VDD out[174] sky130_fd_sc_hd__buf_8 
Xg4871 pass[16] VSS VSS VDD VDD out[16] sky130_fd_sc_hd__buf_8 
Xg5038 pass[90] VSS VSS VDD VDD out[90] sky130_fd_sc_hd__buf_8 
Xg5083 pass[60] VSS VSS VDD VDD out[60] sky130_fd_sc_hd__buf_8 
Xg4957 pass[105] VSS VSS VDD VDD out[105] sky130_fd_sc_hd__buf_8 
Xg4897 pass[191] VSS VSS VDD VDD out[191] sky130_fd_sc_hd__buf_8 
Xg4975 pass[64] VSS VSS VDD VDD out[64] sky130_fd_sc_hd__buf_8 
Xg4930 pass[61] VSS VSS VDD VDD out[61] sky130_fd_sc_hd__buf_8 
Xg4952 pass[241] VSS VSS VDD VDD out[241] sky130_fd_sc_hd__buf_8 
Xg4985 pass[19] VSS VSS VDD VDD out[19] sky130_fd_sc_hd__buf_8 
Xg5029 pass[196] VSS VSS VDD VDD out[196] sky130_fd_sc_hd__buf_8 
Xg4859 pass[242] VSS VSS VDD VDD out[242] sky130_fd_sc_hd__buf_8 
Xg5057 pass[250] VSS VSS VDD VDD out[250] sky130_fd_sc_hd__buf_8 
Xg4920 pass[154] VSS VSS VDD VDD out[154] sky130_fd_sc_hd__buf_8 
Xg5096 pass[28] VSS VSS VDD VDD out[28] sky130_fd_sc_hd__buf_8 
Xg5047 pass[22] VSS VSS VDD VDD out[22] sky130_fd_sc_hd__buf_8 
Xg4921 pass[205] VSS VSS VDD VDD out[205] sky130_fd_sc_hd__buf_8 
Xg4904 pass[251] VSS VSS VDD VDD out[251] sky130_fd_sc_hd__buf_8 
Xg5071 pass[201] VSS VSS VDD VDD out[201] sky130_fd_sc_hd__buf_8 
Xg5026 pass[195] VSS VSS VDD VDD out[195] sky130_fd_sc_hd__buf_8 
Xg4887 pass[229] VSS VSS VDD VDD out[229] sky130_fd_sc_hd__buf_8 
Xg4997 pass[230] VSS VSS VDD VDD out[230] sky130_fd_sc_hd__buf_8 
Xg5054 pass[206] VSS VSS VDD VDD out[206] sky130_fd_sc_hd__buf_8 
Xg5076 pass[73] VSS VSS VDD VDD out[73] sky130_fd_sc_hd__buf_8 
Xg4874 pass[20] VSS VSS VDD VDD out[20] sky130_fd_sc_hd__buf_8 
Xg4936 pass[75] VSS VSS VDD VDD out[75] sky130_fd_sc_hd__buf_8 
Xg4853 pass[232] VSS VSS VDD VDD out[232] sky130_fd_sc_hd__buf_8 
Xg4901 pass[231] VSS VSS VDD VDD out[231] sky130_fd_sc_hd__buf_8 
Xg4895 pass[95] VSS VSS VDD VDD out[95] sky130_fd_sc_hd__buf_8 
Xg4955 pass[18] VSS VSS VDD VDD out[18] sky130_fd_sc_hd__buf_8 
Xg4866 pass[71] VSS VSS VDD VDD out[71] sky130_fd_sc_hd__buf_8 
Xg4850 pass[69] VSS VSS VDD VDD out[69] sky130_fd_sc_hd__buf_8 
Xg5065 pass[10] VSS VSS VDD VDD out[10] sky130_fd_sc_hd__buf_8 
Xg4931 pass[159] VSS VSS VDD VDD out[159] sky130_fd_sc_hd__buf_8 
Xg4917 pass[89] VSS VSS VDD VDD out[89] sky130_fd_sc_hd__buf_8 
Xg5091 pass[9] VSS VSS VDD VDD out[9] sky130_fd_sc_hd__buf_8 
Xg4965 pass[177] VSS VSS VDD VDD out[177] sky130_fd_sc_hd__buf_8 
Xg5020 pass[1] VSS VSS VDD VDD out[1] sky130_fd_sc_hd__buf_8 
Xg5009 pass[188] VSS VSS VDD VDD out[188] sky130_fd_sc_hd__buf_8 
Xg4971 pass[169] VSS VSS VDD VDD out[169] sky130_fd_sc_hd__buf_8 
Xg5023 pass[225] VSS VSS VDD VDD out[225] sky130_fd_sc_hd__buf_8 
Xg4845 pass[0] VSS VSS VDD VDD out[0] sky130_fd_sc_hd__buf_8 
Xg5056 pass[49] VSS VSS VDD VDD out[49] sky130_fd_sc_hd__buf_8 
Xg5072 pass[148] VSS VSS VDD VDD out[148] sky130_fd_sc_hd__buf_8 
Xg4912 pass[155] VSS VSS VDD VDD out[155] sky130_fd_sc_hd__buf_8 
Xg5051 pass[2] VSS VSS VDD VDD out[2] sky130_fd_sc_hd__buf_8 
Xg5088 pass[146] VSS VSS VDD VDD out[146] sky130_fd_sc_hd__buf_8 
Xg4880 pass[48] VSS VSS VDD VDD out[48] sky130_fd_sc_hd__buf_8 
Xg5010 pass[47] VSS VSS VDD VDD out[47] sky130_fd_sc_hd__buf_8 
Xg4927 pass[59] VSS VSS VDD VDD out[59] sky130_fd_sc_hd__buf_8 
Xg5013 pass[254] VSS VSS VDD VDD n_254 sky130_fd_sc_hd__clkbuf_1 
Xg4972 n_536 VSS VSS VDD VDD n_510 sky130_fd_sc_hd__inv_16 
Xg5080 pass[54] VSS VSS VDD VDD out[54] sky130_fd_sc_hd__buf_8 
Xg5082 pass[46] VSS VSS VDD VDD out[46] sky130_fd_sc_hd__buf_8 
Xg4988 pass[24] VSS VSS VDD VDD out[24] sky130_fd_sc_hd__buf_8 
Xg5086 pass[226] VSS VSS VDD VDD out[226] sky130_fd_sc_hd__buf_8 
Xg5021 pass[186] VSS VSS VDD VDD out[186] sky130_fd_sc_hd__buf_8 
Xg4885 pass[168] VSS VSS VDD VDD out[168] sky130_fd_sc_hd__buf_8 
Xg4987 pass[190] VSS VSS VDD VDD out[190] sky130_fd_sc_hd__buf_8 
Xg4868 pass[138] VSS VSS VDD VDD out[138] sky130_fd_sc_hd__buf_8 
Xg4905 pass[43] VSS VSS VDD VDD out[43] sky130_fd_sc_hd__buf_8 
Xg4963 pass[109] VSS VSS VDD VDD out[109] sky130_fd_sc_hd__buf_8 
Xg4974 pass[42] VSS VSS VDD VDD out[42] sky130_fd_sc_hd__buf_8 
Xg4869 pass[136] VSS VSS VDD VDD out[136] sky130_fd_sc_hd__buf_8 
Xg5070 pass[228] VSS VSS VDD VDD out[228] sky130_fd_sc_hd__buf_8 
Xg5019 pass[203] VSS VSS VDD VDD out[203] sky130_fd_sc_hd__buf_8 
Xg4999 pass[167] VSS VSS VDD VDD out[167] sky130_fd_sc_hd__buf_8 
Xg4990 pass[134] VSS VSS VDD VDD out[134] sky130_fd_sc_hd__buf_8 
Xg4890 pass[41] VSS VSS VDD VDD out[41] sky130_fd_sc_hd__buf_8 
Xg5018 pass[253] VSS VSS VDD VDD out[253] sky130_fd_sc_hd__buf_8 
Xg5046 pass[97] VSS VSS VDD VDD out[97] sky130_fd_sc_hd__buf_8 
Xg4995 pass[130] VSS VSS VDD VDD out[130] sky130_fd_sc_hd__buf_8 
Xg5041 pass[40] VSS VSS VDD VDD out[40] sky130_fd_sc_hd__buf_8 
Xg4941 pass[7] VSS VSS VDD VDD out[7] sky130_fd_sc_hd__buf_8 
Xg4996 pass[129] VSS VSS VDD VDD out[129] sky130_fd_sc_hd__buf_8 
Xg4940 pass[39] VSS VSS VDD VDD out[39] sky130_fd_sc_hd__buf_8 
Xg4851 pass[81] VSS VSS VDD VDD out[81] sky130_fd_sc_hd__buf_8 
Xg4857 pass[123] VSS VSS VDD VDD out[123] sky130_fd_sc_hd__buf_8 
Xg4881 pass[36] VSS VSS VDD VDD out[36] sky130_fd_sc_hd__buf_8 
Xg5040 pass[213] VSS VSS VDD VDD out[213] sky130_fd_sc_hd__buf_8 
Xg5002 pass[124] VSS VSS VDD VDD out[124] sky130_fd_sc_hd__buf_8 
Xg4899 pass[125] VSS VSS VDD VDD out[125] sky130_fd_sc_hd__buf_8 
Xg5101 pass[84] VSS VSS VDD VDD out[84] sky130_fd_sc_hd__buf_8 
Xg5014 pass[128] VSS VSS VDD VDD out[128] sky130_fd_sc_hd__buf_8 
Xg5058 pass[173] VSS VSS VDD VDD out[173] sky130_fd_sc_hd__buf_8 
Xg5024 pass[236] VSS VSS VDD VDD out[236] sky130_fd_sc_hd__buf_8 
Xg4916 pass[120] VSS VSS VDD VDD out[120] sky130_fd_sc_hd__buf_8 
Xg4953 pass[181] VSS VSS VDD VDD out[181] sky130_fd_sc_hd__buf_8 
Xg4914 pass[119] VSS VSS VDD VDD out[119] sky130_fd_sc_hd__buf_8 
Xg4922 pass[58] VSS VSS VDD VDD out[58] sky130_fd_sc_hd__buf_8 
Xg4980 pass[80] VSS VSS VDD VDD out[80] sky130_fd_sc_hd__buf_8 
Xg4878 pass[65] VSS VSS VDD VDD out[65] sky130_fd_sc_hd__buf_8 
Xg4889 pass[116] VSS VSS VDD VDD out[116] sky130_fd_sc_hd__buf_8 
Xg4960 pass[140] VSS VSS VDD VDD out[140] sky130_fd_sc_hd__buf_8 
Xg4900 pass[57] VSS VSS VDD VDD out[57] sky130_fd_sc_hd__buf_8 
Xg4968 pass[113] VSS VSS VDD VDD out[113] sky130_fd_sc_hd__buf_8 
Xg5084 pass[6] VSS VSS VDD VDD out[6] sky130_fd_sc_hd__buf_8 
Xg4861 pass[29] VSS VSS VDD VDD out[29] sky130_fd_sc_hd__buf_8 
Xg4969 pass[77] VSS VSS VDD VDD out[77] sky130_fd_sc_hd__buf_8 
Xg4966 pass[247] VSS VSS VDD VDD out[247] sky130_fd_sc_hd__buf_8 
Xg5100 pass[200] VSS VSS VDD VDD out[200] sky130_fd_sc_hd__buf_8 
Xg4956 pass[93] VSS VSS VDD VDD out[93] sky130_fd_sc_hd__buf_8 
Xg5099 pass[161] VSS VSS VDD VDD out[161] sky130_fd_sc_hd__buf_8 
Xg5037 pass[101] VSS VSS VDD VDD out[101] sky130_fd_sc_hd__buf_8 
Xg5006 pass[152] VSS VSS VDD VDD out[152] sky130_fd_sc_hd__buf_8 
Xg4925 pass[56] VSS VSS VDD VDD out[56] sky130_fd_sc_hd__buf_8 
Xg5068 pass[72] VSS VSS VDD VDD out[72] sky130_fd_sc_hd__buf_8 
Xg5025 pass[11] VSS VSS VDD VDD out[11] sky130_fd_sc_hd__buf_8 
Xg5089 pass[149] VSS VSS VDD VDD out[149] sky130_fd_sc_hd__buf_8 
Xg4882 pass[52] VSS VSS VDD VDD out[52] sky130_fd_sc_hd__buf_8 
Xg4888 pass[4] VSS VSS VDD VDD out[4] sky130_fd_sc_hd__buf_8 
Xg4879 pass[94] VSS VSS VDD VDD out[94] sky130_fd_sc_hd__buf_8 
Xg5027 pass[103] VSS VSS VDD VDD out[103] sky130_fd_sc_hd__buf_8 
Xg5011 pass[88] VSS VSS VDD VDD out[88] sky130_fd_sc_hd__buf_8 
Xg5060 pass[99] VSS VSS VDD VDD out[99] sky130_fd_sc_hd__buf_8 
Xg5093 pass[235] VSS VSS VDD VDD out[235] sky130_fd_sc_hd__buf_8 
Xg4928 pass[87] VSS VSS VDD VDD out[87] sky130_fd_sc_hd__buf_8 
Xg4909 pass[151] VSS VSS VDD VDD out[151] sky130_fd_sc_hd__buf_8 
Xg5055 pass[249] VSS VSS VDD VDD out[249] sky130_fd_sc_hd__buf_8 
Xg5030 pass[240] VSS VSS VDD VDD out[240] sky130_fd_sc_hd__buf_8 
Xg5039 pass[86] VSS VSS VDD VDD out[86] sky130_fd_sc_hd__buf_8 
Xg5074 pass[145] VSS VSS VDD VDD out[145] sky130_fd_sc_hd__buf_8 
Xg4977 pass[147] VSS VSS VDD VDD out[147] sky130_fd_sc_hd__buf_8 
Xg5095 pass[224] VSS VSS VDD VDD out[224] sky130_fd_sc_hd__buf_8 
Xg5016 pass[239] VSS VSS VDD VDD out[239] sky130_fd_sc_hd__buf_8 
Xg4891 pass[85] VSS VSS VDD VDD out[85] sky130_fd_sc_hd__buf_8 
Xg4908 pass[162] VSS VSS VDD VDD out[162] sky130_fd_sc_hd__buf_8 
Xg4876 pass[223] VSS VSS VDD VDD out[223] sky130_fd_sc_hd__buf_8 
Xg4954 pass[17] VSS VSS VDD VDD out[17] sky130_fd_sc_hd__buf_8 
Xg5098 pass[144] VSS VSS VDD VDD out[144] sky130_fd_sc_hd__buf_8 
Xg5015 pass[156] VSS VSS VDD VDD out[156] sky130_fd_sc_hd__buf_8 
Xg5033 pass[26] VSS VSS VDD VDD out[26] sky130_fd_sc_hd__buf_8 
Xg4983 pass[238] VSS VSS VDD VDD out[238] sky130_fd_sc_hd__buf_8 
Xg5066 pass[142] VSS VSS VDD VDD out[142] sky130_fd_sc_hd__buf_8 
Xg4910 pass[222] VSS VSS VDD VDD out[222] sky130_fd_sc_hd__buf_8 
Xg5069 pass[150] VSS VSS VDD VDD out[150] sky130_fd_sc_hd__buf_8 
Xg5073 pass[68] VSS VSS VDD VDD out[68] sky130_fd_sc_hd__buf_8 
Xg4919 pass[153] VSS VSS VDD VDD out[153] sky130_fd_sc_hd__buf_8 
Xg4978 pass[8] VSS VSS VDD VDD out[8] sky130_fd_sc_hd__buf_8 
Xg5092 pass[244] VSS VSS VDD VDD out[244] sky130_fd_sc_hd__buf_8 
Xg4984 pass[106] VSS VSS VDD VDD out[106] sky130_fd_sc_hd__buf_8 
Xg4913 pass[67] VSS VSS VDD VDD out[67] sky130_fd_sc_hd__buf_8 
Xg4961 pass[185] VSS VSS VDD VDD out[185] sky130_fd_sc_hd__buf_8 
Xg4989 pass[92] VSS VSS VDD VDD out[92] sky130_fd_sc_hd__buf_8 
Xg5042 pass[66] VSS VSS VDD VDD out[66] sky130_fd_sc_hd__buf_8 
Xg4998 pass[35] VSS VSS VDD VDD out[35] sky130_fd_sc_hd__buf_8 
Xg4864 pass[182] VSS VSS VDD VDD out[182] sky130_fd_sc_hd__buf_8 
Xg5048 pass[23] VSS VSS VDD VDD out[23] sky130_fd_sc_hd__buf_8 
Xg4926 pass[157] VSS VSS VDD VDD out[157] sky130_fd_sc_hd__buf_8 
Xg5049 pass[33] VSS VSS VDD VDD out[33] sky130_fd_sc_hd__buf_8 
Xg4942 pass[194] VSS VSS VDD VDD out[194] sky130_fd_sc_hd__buf_8 
Xg4873 pass[25] VSS VSS VDD VDD out[25] sky130_fd_sc_hd__buf_8 
Xg4929 pass[176] VSS VSS VDD VDD out[176] sky130_fd_sc_hd__buf_8 
Xg4950 pass[180] VSS VSS VDD VDD out[180] sky130_fd_sc_hd__buf_8 
Xg5077 pass[237] VSS VSS VDD VDD out[237] sky130_fd_sc_hd__buf_8 
Xg4949 pass[199] VSS VSS VDD VDD out[199] sky130_fd_sc_hd__buf_8 
Xg4947 pass[13] VSS VSS VDD VDD out[13] sky130_fd_sc_hd__buf_8 
Xg4863 pass[141] VSS VSS VDD VDD out[141] sky130_fd_sc_hd__buf_8 
Xg4967 pass[179] VSS VSS VDD VDD out[179] sky130_fd_sc_hd__buf_8 
Xg4958 pass[21] VSS VSS VDD VDD out[21] sky130_fd_sc_hd__buf_8 
Xg4852 pass[221] VSS VSS VDD VDD out[221] sky130_fd_sc_hd__buf_8 
Xg4951 pass[107] VSS VSS VDD VDD out[107] sky130_fd_sc_hd__buf_8 
Xg5094 pass[45] VSS VSS VDD VDD out[45] sky130_fd_sc_hd__buf_8 
Xg5000 pass[44] VSS VSS VDD VDD out[44] sky130_fd_sc_hd__buf_8 
Xg4944 pass[220] VSS VSS VDD VDD out[220] sky130_fd_sc_hd__buf_8 
Xg5067 pass[139] VSS VSS VDD VDD out[139] sky130_fd_sc_hd__buf_8 
Xg4973 pass[245] VSS VSS VDD VDD out[245] sky130_fd_sc_hd__buf_8 
Xg4986 pass[137] VSS VSS VDD VDD out[137] sky130_fd_sc_hd__buf_8 
Xg4959 pass[219] VSS VSS VDD VDD out[219] sky130_fd_sc_hd__buf_8 
Xg5090 pass[218] VSS VSS VDD VDD out[218] sky130_fd_sc_hd__buf_8 
Xg4854 pass[135] VSS VSS VDD VDD out[135] sky130_fd_sc_hd__buf_8 
Xg4865 pass[198] VSS VSS VDD VDD out[198] sky130_fd_sc_hd__buf_8 
Xg4896 pass[83] VSS VSS VDD VDD out[83] sky130_fd_sc_hd__buf_8 
Xg4993 pass[133] VSS VSS VDD VDD out[133] sky130_fd_sc_hd__buf_8 
Xg4906 pass[53] VSS VSS VDD VDD out[53] sky130_fd_sc_hd__buf_8 
Xg4935 pass[217] VSS VSS VDD VDD out[217] sky130_fd_sc_hd__buf_8 
Xg4992 pass[132] VSS VSS VDD VDD out[132] sky130_fd_sc_hd__buf_8 
Xg5050 pass[131] VSS VSS VDD VDD out[131] sky130_fd_sc_hd__buf_8 
Xg4937 pass[82] VSS VSS VDD VDD out[82] sky130_fd_sc_hd__buf_8 
Xg4847 pass[187] VSS VSS VDD VDD out[187] sky130_fd_sc_hd__buf_8 
Xhi_fo_buf n_525 VSS VSS VDD VDD n_517 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5358 n_525 VSS VSS VDD VDD n_521 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5359 comp_in VSS VSS VDD VDD n_525 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5360 n_534 VSS VSS VDD VDD n_526 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5361 n_534 VSS VSS VDD VDD n_530 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5362 comp_in VSS VSS VDD VDD n_534 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5363 comp_in VSS VSS VDD VDD n_536 sky130_fd_sc_hd__buf_6 
Xhi_fo_buf5364 n_545 VSS VSS VDD VDD n_537 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5365 n_545 VSS VSS VDD VDD n_541 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5366 comp_in VSS VSS VDD VDD n_545 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5367 n_554 VSS VSS VDD VDD n_546 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5368 n_554 VSS VSS VDD VDD n_550 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5369 comp_in VSS VSS VDD VDD n_554 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5370 n_564 VSS VSS VDD VDD n_556 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5371 n_564 VSS VSS VDD VDD n_560 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5372 comp_in VSS VSS VDD VDD n_564 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5373 n_573 VSS VSS VDD VDD n_565 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5374 n_573 VSS VSS VDD VDD n_569 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5375 comp_in VSS VSS VDD VDD n_573 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5376 n_583 VSS VSS VDD VDD n_575 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5377 n_583 VSS VSS VDD VDD n_579 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5378 comp_in VSS VSS VDD VDD n_583 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5379 n_592 VSS VSS VDD VDD n_584 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5380 n_592 VSS VSS VDD VDD n_588 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5381 comp_in VSS VSS VDD VDD n_592 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5382 n_602 VSS VSS VDD VDD n_594 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5383 n_602 VSS VSS VDD VDD n_598 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5384 comp_in VSS VSS VDD VDD n_602 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5385 n_611 VSS VSS VDD VDD n_603 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5386 n_611 VSS VSS VDD VDD n_607 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5387 comp_in VSS VSS VDD VDD n_611 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5388 n_621 VSS VSS VDD VDD n_613 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5389 n_621 VSS VSS VDD VDD n_617 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5390 comp_in VSS VSS VDD VDD n_621 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5391 n_630 VSS VSS VDD VDD n_622 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5392 n_630 VSS VSS VDD VDD n_626 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5393 comp_in VSS VSS VDD VDD n_630 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5394 n_648 VSS VSS VDD VDD n_632 sky130_fd_sc_hd__clkinv_4 
Xhi_fo_buf5395 n_648 VSS VSS VDD VDD n_640 sky130_fd_sc_hd__clkinv_4 
Xhi_fo_buf5396 n_648 VSS VSS VDD VDD n_649 sky130_fd_sc_hd__clkinv_8 
Xhi_fo_buf5397 comp_in VSS VSS VDD VDD n_648 sky130_fd_sc_hd__clkinv_8 
Xhi_fo_buf5398 rst VSS VSS VDD VDD n_664 sky130_fd_sc_hd__buf_6 
Xhi_fo_buf5399 rst VSS VSS VDD VDD n_680 sky130_fd_sc_hd__buf_6 
Xhi_fo_buf5400 rst VSS VSS VDD VDD n_697 sky130_fd_sc_hd__buf_6 
Xhi_fo_buf5401 rst VSS VSS VDD VDD n_713 sky130_fd_sc_hd__buf_6 
Xhi_fo_buf5402 rst VSS VSS VDD VDD n_730 sky130_fd_sc_hd__buf_6 
Xhi_fo_buf5403 rst VSS VSS VDD VDD n_746 sky130_fd_sc_hd__buf_6 
Xhi_fo_buf5404 rst VSS VSS VDD VDD n_763 sky130_fd_sc_hd__buf_6 
Xhi_fo_buf5405 rst VSS VSS VDD VDD n_779 sky130_fd_sc_hd__buf_6 
Xhi_fo_buf5406 n_804 VSS VSS VDD VDD n_796 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5407 n_804 VSS VSS VDD VDD n_800 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5408 n_510 VSS VSS VDD VDD n_804 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5409 n_813 VSS VSS VDD VDD n_805 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5410 n_813 VSS VSS VDD VDD n_809 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5411 n_510 VSS VSS VDD VDD n_813 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5412 n_823 VSS VSS VDD VDD n_815 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5413 n_823 VSS VSS VDD VDD n_819 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5414 n_510 VSS VSS VDD VDD n_823 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5415 n_832 VSS VSS VDD VDD n_824 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5416 n_832 VSS VSS VDD VDD n_828 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5417 n_510 VSS VSS VDD VDD n_832 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5418 n_842 VSS VSS VDD VDD n_834 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5419 n_842 VSS VSS VDD VDD n_838 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5420 n_510 VSS VSS VDD VDD n_842 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5421 n_851 VSS VSS VDD VDD n_843 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5422 n_851 VSS VSS VDD VDD n_847 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5423 n_510 VSS VSS VDD VDD n_851 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5424 n_861 VSS VSS VDD VDD n_853 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5425 n_861 VSS VSS VDD VDD n_857 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5426 n_510 VSS VSS VDD VDD n_861 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5427 n_870 VSS VSS VDD VDD n_862 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5428 n_870 VSS VSS VDD VDD n_866 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5429 n_510 VSS VSS VDD VDD n_870 sky130_fd_sc_hd__inv_2 
Xhi_fo_buf5430 n_888 VSS VSS VDD VDD n_872 sky130_fd_sc_hd__clkinv_4 
Xhi_fo_buf5431 n_888 VSS VSS VDD VDD n_880 sky130_fd_sc_hd__clkinv_4 
Xhi_fo_buf5432 n_888 VSS VSS VDD VDD n_889 sky130_fd_sc_hd__clkinv_4 
Xhi_fo_buf5433 n_888 VSS VSS VDD VDD n_897 sky130_fd_sc_hd__clkinv_4 
Xhi_fo_buf5434 n_888 VSS VSS VDD VDD n_906 sky130_fd_sc_hd__clkinv_4 
Xhi_fo_buf5435 n_888 VSS VSS VDD VDD n_914 sky130_fd_sc_hd__clkinv_4 
Xhi_fo_buf5436 n_888 VSS VSS VDD VDD n_923 sky130_fd_sc_hd__clkinv_8 
Xhi_fo_buf5437 n_510 VSS VSS VDD VDD n_888 sky130_fd_sc_hd__clkinv_8 
.ENDS
